package net.mcreator.fbms.block.listener;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.mcreator.fbms.init.FbmsModBlockEntities;
import net.mcreator.fbms.block.renderer.WitheredWallyWalrusTileRenderer;
import net.mcreator.fbms.block.renderer.WitheredPuffyPuffinsTileRenderer;
import net.mcreator.fbms.block.renderer.WitheredHazyReindeerTileRenderer;
import net.mcreator.fbms.block.renderer.WitheredDougTheDogTileRenderer;
import net.mcreator.fbms.block.renderer.WinkSignTileRenderer;
import net.mcreator.fbms.block.renderer.WallyWalrusTileRenderer;
import net.mcreator.fbms.block.renderer.WallyWalrusAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.ToyPugTileRenderer;
import net.mcreator.fbms.block.renderer.ToyFreddyTileRenderer;
import net.mcreator.fbms.block.renderer.ToyFoxyTileRenderer;
import net.mcreator.fbms.block.renderer.ToyChicaTileRenderer;
import net.mcreator.fbms.block.renderer.ToyBonnieTileRenderer;
import net.mcreator.fbms.block.renderer.TheMangleTileRenderer;
import net.mcreator.fbms.block.renderer.StephanPlushTileRenderer;
import net.mcreator.fbms.block.renderer.StationWagonBlockTileRenderer;
import net.mcreator.fbms.block.renderer.StEndoTileRenderer;
import net.mcreator.fbms.block.renderer.StEndoAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.Springbonnie01TileRenderer;
import net.mcreator.fbms.block.renderer.Springbonnie01AnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.SignSNSTileRenderer;
import net.mcreator.fbms.block.renderer.SignSBTTileRenderer;
import net.mcreator.fbms.block.renderer.SignRFATileRenderer;
import net.mcreator.fbms.block.renderer.SignMSTileRenderer;
import net.mcreator.fbms.block.renderer.SignDDWTileRenderer;
import net.mcreator.fbms.block.renderer.ShredBearTileRenderer;
import net.mcreator.fbms.block.renderer.SecurityPuppetTileRenderer;
import net.mcreator.fbms.block.renderer.ScrapTrapTileRenderer;
import net.mcreator.fbms.block.renderer.SanitationStationTileRenderer;
import net.mcreator.fbms.block.renderer.SalvagedJollyTileRenderer;
import net.mcreator.fbms.block.renderer.RustyTileRenderer;
import net.mcreator.fbms.block.renderer.RustyAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.RottenPitTileRenderer;
import net.mcreator.fbms.block.renderer.RoseyTileRenderer;
import net.mcreator.fbms.block.renderer.RockStarFreddyTileRenderer;
import net.mcreator.fbms.block.renderer.RockStarFreddyAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.RockStarFoxyTileRenderer;
import net.mcreator.fbms.block.renderer.RockStarFoxyAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.RockStarChicaTileRenderer;
import net.mcreator.fbms.block.renderer.RockStarChicaAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.RockStarBonnieTileRenderer;
import net.mcreator.fbms.block.renderer.RockStarBonnieAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.RidingRocketsRedTileRenderer;
import net.mcreator.fbms.block.renderer.RidingRocketsPurpleTileRenderer;
import net.mcreator.fbms.block.renderer.RetroChicaTileRenderer;
import net.mcreator.fbms.block.renderer.RetroChicaAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.RestRoomSignTileRenderer;
import net.mcreator.fbms.block.renderer.RascTileRenderer;
import net.mcreator.fbms.block.renderer.PuppetBoxTileRenderer;
import net.mcreator.fbms.block.renderer.PuffyPuffinsTileRenderer;
import net.mcreator.fbms.block.renderer.PuffyPuffinsAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.ProjectorTileRenderer;
import net.mcreator.fbms.block.renderer.ProjectionTileRenderer;
import net.mcreator.fbms.block.renderer.PrizeKingTileRenderer;
import net.mcreator.fbms.block.renderer.PrizeCounterSignTileRenderer;
import net.mcreator.fbms.block.renderer.PizzaPlaceSignTileRenderer;
import net.mcreator.fbms.block.renderer.PizzaPlaceSignOldTileRenderer;
import net.mcreator.fbms.block.renderer.PizzaBox93OpenTileRenderer;
import net.mcreator.fbms.block.renderer.PizzaBox93ClosedTileRenderer;
import net.mcreator.fbms.block.renderer.PizzaBox87OpenTileRenderer;
import net.mcreator.fbms.block.renderer.PizzaBox87ClosedTileRenderer;
import net.mcreator.fbms.block.renderer.PizzaBox85OpenTileRenderer;
import net.mcreator.fbms.block.renderer.PizzaBox85ClosedTileRenderer;
import net.mcreator.fbms.block.renderer.PizzaBox24OpenTileRenderer;
import net.mcreator.fbms.block.renderer.PizzaBox24ClosedTileRenderer;
import net.mcreator.fbms.block.renderer.PinballToyFreddyTileRenderer;
import net.mcreator.fbms.block.renderer.PinTheBowtieOnTheTieTheToyFreddyTileRenderer;
import net.mcreator.fbms.block.renderer.PinTheBowtieOnTheFreddyTileRenderer;
import net.mcreator.fbms.block.renderer.PigPatchTileRenderer;
import net.mcreator.fbms.block.renderer.PigPatchAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.PicklesTileRenderer;
import net.mcreator.fbms.block.renderer.PartyRoomSignTileRenderer;
import net.mcreator.fbms.block.renderer.PaperPlatesTileRenderer;
import net.mcreator.fbms.block.renderer.PanStanTileRenderer;
import net.mcreator.fbms.block.renderer.PCTileRenderer;
import net.mcreator.fbms.block.renderer.OrvilleTileRenderer;
import net.mcreator.fbms.block.renderer.OrvilleAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.OldFreddyTileRenderer;
import net.mcreator.fbms.block.renderer.OldFoxyTileRenderer;
import net.mcreator.fbms.block.renderer.OldChicaTileRenderer;
import net.mcreator.fbms.block.renderer.OldBonnieTileRenderer;
import net.mcreator.fbms.block.renderer.Number1CrateTileRenderer;
import net.mcreator.fbms.block.renderer.NoveltyTrafficLightTileRenderer;
import net.mcreator.fbms.block.renderer.NeonYellowLightStripTileRenderer;
import net.mcreator.fbms.block.renderer.NeonYellowLightStripRightTileRenderer;
import net.mcreator.fbms.block.renderer.NeonYellowLightStripLeftTileRenderer;
import net.mcreator.fbms.block.renderer.NeonStageLightsPinkTileRenderer;
import net.mcreator.fbms.block.renderer.NeonStageLightsOrangeTileRenderer;
import net.mcreator.fbms.block.renderer.NeonStageLightsBlueTileRenderer;
import net.mcreator.fbms.block.renderer.NeonStageLightGreenTileRenderer;
import net.mcreator.fbms.block.renderer.NeonRedLightStripTileRenderer;
import net.mcreator.fbms.block.renderer.NeonRedLightStripRightTileRenderer;
import net.mcreator.fbms.block.renderer.NeonRedLightStripLeftTileRenderer;
import net.mcreator.fbms.block.renderer.NeonPartySet4TileRenderer;
import net.mcreator.fbms.block.renderer.NeonPartySet3TileRenderer;
import net.mcreator.fbms.block.renderer.NeonPartySet2TileRenderer;
import net.mcreator.fbms.block.renderer.NeonPartySet1TileRenderer;
import net.mcreator.fbms.block.renderer.NeonOrangeLightStripTileRenderer;
import net.mcreator.fbms.block.renderer.NeonOrangeLightStripRightTileRenderer;
import net.mcreator.fbms.block.renderer.NeonOrangeLightLeftTileRenderer;
import net.mcreator.fbms.block.renderer.NeonJukeBoxTileRenderer;
import net.mcreator.fbms.block.renderer.NeonJukeBoxOffTileRenderer;
import net.mcreator.fbms.block.renderer.NeonGreenLightStripTileRenderer;
import net.mcreator.fbms.block.renderer.NeonGreenLightStripRightTileRenderer;
import net.mcreator.fbms.block.renderer.NeonGreenLightStripLeftTileRenderer;
import net.mcreator.fbms.block.renderer.NeonBlueLightStripTileRenderer;
import net.mcreator.fbms.block.renderer.NeonBlueLightStripRightTileRenderer;
import net.mcreator.fbms.block.renderer.NeonBlueLightStripLeftTileRenderer;
import net.mcreator.fbms.block.renderer.NeddBearTileRenderer;
import net.mcreator.fbms.block.renderer.NeddBearAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.MusicManTileRenderer;
import net.mcreator.fbms.block.renderer.MusicManAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.MrHugsTileRenderer;
import net.mcreator.fbms.block.renderer.MrHippoTileRenderer;
import net.mcreator.fbms.block.renderer.MrHippoAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.MrCanDoTileRenderer;
import net.mcreator.fbms.block.renderer.MoltenSitTileRenderer;
import net.mcreator.fbms.block.renderer.MoltenFreddyTileRenderer;
import net.mcreator.fbms.block.renderer.MoldyRabbitTileRenderer;
import net.mcreator.fbms.block.renderer.MidnightMotoristTileRenderer;
import net.mcreator.fbms.block.renderer.Megaultimatespeakertron3000TileRenderer;
import net.mcreator.fbms.block.renderer.LolbitRecordTileRenderer;
import net.mcreator.fbms.block.renderer.LolBitTileRenderer;
import net.mcreator.fbms.block.renderer.LolBitDtTileRenderer;
import net.mcreator.fbms.block.renderer.LolBit409TileRenderer;
import net.mcreator.fbms.block.renderer.LemonadeClownTileRenderer;
import net.mcreator.fbms.block.renderer.LeftyTileRenderer;
import net.mcreator.fbms.block.renderer.LeftyAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.LargeSignTileRenderer;
import net.mcreator.fbms.block.renderer.LargeSign4TileRenderer;
import net.mcreator.fbms.block.renderer.LargeSign3TileRenderer;
import net.mcreator.fbms.block.renderer.LargeSign2TileRenderer;
import net.mcreator.fbms.block.renderer.LadderTowerTileRenderer;
import net.mcreator.fbms.block.renderer.KitchenSignTileRenderer;
import net.mcreator.fbms.block.renderer.JollyTheRatTileRenderer;
import net.mcreator.fbms.block.renderer.JollyTheRatAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.JeffsPizzaSignTileRenderer;
import net.mcreator.fbms.block.renderer.IndigoTileRenderer;
import net.mcreator.fbms.block.renderer.ImpalaBlockTileRenderer;
import net.mcreator.fbms.block.renderer.IgnitedChicaTileRenderer;
import net.mcreator.fbms.block.renderer.HelpyCutOutTileRenderer;
import net.mcreator.fbms.block.renderer.HeavyDuityDoorTileRenderer;
import net.mcreator.fbms.block.renderer.HeavyDuityDoorClosedTileRenderer;
import net.mcreator.fbms.block.renderer.HazyReindeerTileRenderer;
import net.mcreator.fbms.block.renderer.HazyReindeerAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.HappyFrogTileRenderer;
import net.mcreator.fbms.block.renderer.HappYFrogAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.GusThePugTileRenderer;
import net.mcreator.fbms.block.renderer.GusThePugAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.GtEndoTileRenderer;
import net.mcreator.fbms.block.renderer.GtEndoAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.GravityVortexTileRenderer;
import net.mcreator.fbms.block.renderer.GravityVortex2TileRenderer;
import net.mcreator.fbms.block.renderer.GarfPlushTileRenderer;
import net.mcreator.fbms.block.renderer.FuntimeDelilahblockTileRenderer;
import net.mcreator.fbms.block.renderer.FuntimeDelilahTileRenderer;
import net.mcreator.fbms.block.renderer.FuntimeChicaAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.FunTimeChicaTileRenderer;
import net.mcreator.fbms.block.renderer.FtFreddyTileRenderer;
import net.mcreator.fbms.block.renderer.FtFoxyTileRenderer;
import net.mcreator.fbms.block.renderer.FruityMazeTileRenderer;
import net.mcreator.fbms.block.renderer.FruitPunchClownTileRenderer;
import net.mcreator.fbms.block.renderer.FrightsSignTileRenderer;
import net.mcreator.fbms.block.renderer.FrightsSign2TileRenderer;
import net.mcreator.fbms.block.renderer.FreddyFazBearTileRenderer;
import net.mcreator.fbms.block.renderer.FreddyCutOutTileRenderer;
import net.mcreator.fbms.block.renderer.FredbearDeactivatedTileRenderer;
import net.mcreator.fbms.block.renderer.Fredbear01TileRenderer;
import net.mcreator.fbms.block.renderer.Fredbear01AnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.FredBearTileRenderer;
import net.mcreator.fbms.block.renderer.FoxyTileRenderer;
import net.mcreator.fbms.block.renderer.FoilPartySet4TileRenderer;
import net.mcreator.fbms.block.renderer.FoilPartySet3TileRenderer;
import net.mcreator.fbms.block.renderer.FoilPartySet2TileRenderer;
import net.mcreator.fbms.block.renderer.FoilPartySet1TileRenderer;
import net.mcreator.fbms.block.renderer.EnhancedSpeakerSetTileRenderer;
import net.mcreator.fbms.block.renderer.Endo02TileRenderer;
import net.mcreator.fbms.block.renderer.Endo01TileRenderer;
import net.mcreator.fbms.block.renderer.Endo01AnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.ElChipTileRenderer;
import net.mcreator.fbms.block.renderer.ElChipAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.EggBabyTileRenderer;
import net.mcreator.fbms.block.renderer.DuckPondTileRenderer;
import net.mcreator.fbms.block.renderer.DrTeathTileRenderer;
import net.mcreator.fbms.block.renderer.DougTheDogTileRenderer;
import net.mcreator.fbms.block.renderer.DougTheDogAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.DogeRamBlockTileRenderer;
import net.mcreator.fbms.block.renderer.DocPlushTileRenderer;
import net.mcreator.fbms.block.renderer.DiscountCoolingUnitTileRenderer;
import net.mcreator.fbms.block.renderer.DiscountBallpitTileRenderer;
import net.mcreator.fbms.block.renderer.DeluxeSpeakerSetTileRenderer;
import net.mcreator.fbms.block.renderer.DeluxeBallpitTileRenderer;
import net.mcreator.fbms.block.renderer.DBalloonBoyTileRenderer;
import net.mcreator.fbms.block.renderer.Coins5TileRenderer;
import net.mcreator.fbms.block.renderer.Coins25TileRenderer;
import net.mcreator.fbms.block.renderer.Coins100TileRenderer;
import net.mcreator.fbms.block.renderer.Coins1000TileRenderer;
import net.mcreator.fbms.block.renderer.Coins10000TileRenderer;
import net.mcreator.fbms.block.renderer.CoinTileRenderer;
import net.mcreator.fbms.block.renderer.ChicaTileRenderer;
import net.mcreator.fbms.block.renderer.ChicaCutOutTileRenderer;
import net.mcreator.fbms.block.renderer.CeilingStageLightsTileRenderer;
import net.mcreator.fbms.block.renderer.CeilingStageLightpinkTileRenderer;
import net.mcreator.fbms.block.renderer.CeilingStageLightblueTileRenderer;
import net.mcreator.fbms.block.renderer.CeilingStageLightOrangeTileRenderer;
import net.mcreator.fbms.block.renderer.CarnivalHoopsTileRenderer;
import net.mcreator.fbms.block.renderer.CandyCadetTileRenderer;
import net.mcreator.fbms.block.renderer.CamTileRenderer;
import net.mcreator.fbms.block.renderer.BuffetEndoTileRenderer;
import net.mcreator.fbms.block.renderer.BucketBobTileRenderer;
import net.mcreator.fbms.block.renderer.BrokenFreddyTileRenderer;
import net.mcreator.fbms.block.renderer.BrokenChicaTileRenderer;
import net.mcreator.fbms.block.renderer.BrokenBonnieTileRenderer;
import net.mcreator.fbms.block.renderer.BrokenBarryPolarAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.BonnieTileRenderer;
import net.mcreator.fbms.block.renderer.BonnieCutOutTileRenderer;
import net.mcreator.fbms.block.renderer.BonnetTileRenderer;
import net.mcreator.fbms.block.renderer.BonkABonTileRenderer;
import net.mcreator.fbms.block.renderer.BonBonTileRenderer;
import net.mcreator.fbms.block.renderer.BiteFredBearCutoutTileRenderer;
import net.mcreator.fbms.block.renderer.BarryPolarTileRenderer;
import net.mcreator.fbms.block.renderer.BarryPolarFixedTileRenderer;
import net.mcreator.fbms.block.renderer.BarryPolarAnimatedTileRenderer;
import net.mcreator.fbms.block.renderer.BalloonCartTileRenderer;
import net.mcreator.fbms.block.renderer.BalloonBoyTileRenderer;
import net.mcreator.fbms.block.renderer.BallPitTowerTileRenderer;
import net.mcreator.fbms.block.renderer.BaggyMaggieTileRenderer;
import net.mcreator.fbms.block.renderer.ArcadeSignTileRenderer;
import net.mcreator.fbms.FbmsMod;

@Mod.EventBusSubscriber(modid = FbmsMod.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ClientListener {
	@OnlyIn(Dist.CLIENT)
	@SubscribeEvent
	public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event) {
		event.registerBlockEntityRenderer(FbmsModBlockEntities.CANDY_CADET.get(), context -> new CandyCadetTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.EL_CHIP.get(), context -> new ElChipTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BITE_FRED_BEAR_CUTOUT.get(), context -> new BiteFredBearCutoutTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FUNTIME_CHICA.get(), context -> new FunTimeChicaTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.HAPPY_FROG.get(), context -> new HappyFrogTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LEFTY.get(), context -> new LeftyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.MR_HIPPO.get(), context -> new MrHippoTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEDD_BEAR.get(), context -> new NeddBearTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ORVILLE.get(), context -> new OrvilleTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PRIZE_KING.get(), context -> new PrizeKingTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SECURITY_PUPPET.get(), context -> new SecurityPuppetTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ROCK_STAR_BONNIE.get(), context -> new RockStarBonnieTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ROCK_STAR_CHICA.get(), context -> new RockStarChicaTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ROCK_STAR_FREDDY.get(), context -> new RockStarFreddyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.RUSTY.get(), context -> new RustyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIG_PATCH.get(), context -> new PigPatchTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ROCK_STAR_FOXY.get(), context -> new RockStarFoxyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ENDO_01.get(), context -> new Endo01TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.WINK_SIGN.get(), context -> new WinkSignTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BAGGY_MAGGIE.get(), context -> new BaggyMaggieTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PUPPET_BOX.get(), context -> new PuppetBoxTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LARGE_SIGN.get(), context -> new LargeSignTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LARGE_SIGN_2.get(), context -> new LargeSign2TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SCRAP_TRAP.get(), context -> new ScrapTrapTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.MOLTEN_FREDDY.get(), context -> new MoltenFreddyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FOIL_PARTY_SET_1.get(), context -> new FoilPartySet1TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FOIL_PARTY_SET_2.get(), context -> new FoilPartySet2TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FOIL_PARTY_SET_3.get(), context -> new FoilPartySet3TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FOIL_PARTY_SET_4.get(), context -> new FoilPartySet4TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.DR_TEATH.get(), context -> new DrTeathTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_PARTY_SET_1.get(), context -> new NeonPartySet1TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_PARTY_SET_2.get(), context -> new NeonPartySet2TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_PARTY_SET_3.get(), context -> new NeonPartySet3TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_PARTY_SET_4.get(), context -> new NeonPartySet4TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.MOLDY_RABBIT.get(), context -> new MoldyRabbitTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.MUSIC_MAN.get(), context -> new MusicManTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BARRY_POLAR_ANIMATED.get(), context -> new BarryPolarAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.WITHERED_BARRY_POLAR_ANIMATED.get(), context -> new BrokenBarryPolarAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FUNTIME_DELILAH_ANIMATED.get(), context -> new FuntimeDelilahTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.EL_CHIP_ANIMATED.get(), context -> new ElChipAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ENDO_01_ANIMATED.get(), context -> new Endo01AnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FUNTIME_CHICA_ANIMATED.get(), context -> new FuntimeChicaAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.HAPPY_FROG_ANIMATED.get(), context -> new HappYFrogAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LEFTY_ANIMATED.get(), context -> new LeftyAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.MR_HIPPO_ANIMATED.get(), context -> new MrHippoAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.MUSIC_MAN_ANIMATED.get(), context -> new MusicManAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEDD_BEAR_ANIMATED.get(), context -> new NeddBearAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ORVILLE_ANIMATED.get(), context -> new OrvilleAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIG_PATCH_ANIMATED.get(), context -> new PigPatchAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ROCK_STAR_BONNIE_ANIMATED.get(), context -> new RockStarBonnieAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ROCK_STAR_CHICA_ANIMATED.get(), context -> new RockStarChicaAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ROCK_STAR_FOXY_ANIMATED.get(), context -> new RockStarFoxyAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ROCK_STAR_FREDDY_ANIMATED.get(), context -> new RockStarFreddyAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.RUSTY_ANIMATED.get(), context -> new RustyAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FUNTIME_DELILAH.get(), context -> new FuntimeDelilahblockTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.WITHERED_BARRY_POLAR.get(), context -> new BarryPolarTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BARRY_POLAR.get(), context -> new BarryPolarFixedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.THE_MANGLE.get(), context -> new TheMangleTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LARGE_SIGN_3.get(), context -> new LargeSign3TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LARGE_SIGN_4.get(), context -> new LargeSign4TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SANITATION_STATION.get(), context -> new SanitationStationTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIN_THE_BOWTIE_ON_THE_FREDDY.get(), context -> new PinTheBowtieOnTheFreddyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIN_THE_BOWTIE_ON_THE_TIE_THE_TOY_FREDDY.get(), context -> new PinTheBowtieOnTheTieTheToyFreddyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NOVELTY_TRAFFIC_LIGHT.get(), context -> new NoveltyTrafficLightTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.DUCK_POND.get(), context -> new DuckPondTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.IMPALA_BLOCK.get(), context -> new ImpalaBlockTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.DOGE_RAM_BLOCK.get(), context -> new DogeRamBlockTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.OLD_BONNIE.get(), context -> new OldBonnieTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.OLD_FREDDY.get(), context -> new OldFreddyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.OLD_CHICA.get(), context -> new OldChicaTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.OLD_FOXY.get(), context -> new OldFoxyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.D_BALLOON_BOY.get(), context -> new DBalloonBoyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.DOC_PLUSH.get(), context -> new DocPlushTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.GARF_PLUSH.get(), context -> new GarfPlushTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ROSEY.get(), context -> new RoseyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.STATION_WAGON_BLOCK.get(), context -> new StationWagonBlockTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.DELUXE_SPEAKER_SET.get(), context -> new DeluxeSpeakerSetTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_JUKE_BOX.get(), context -> new NeonJukeBoxTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LADDER_TOWER.get(), context -> new LadderTowerTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BALL_PIT_TOWER.get(), context -> new BallPitTowerTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ENHANCED_SPEAKER_SET.get(), context -> new EnhancedSpeakerSetTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FRUIT_PUNCH_CLOWN.get(), context -> new FruitPunchClownTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LEMONADE_CLOWN.get(), context -> new LemonadeClownTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.DISCOUNT_BALLPIT.get(), context -> new DiscountBallpitTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.EGG_BABY.get(), context -> new EggBabyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.MR_HUGS.get(), context -> new MrHugsTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NUMBER_1_CRATE.get(), context -> new Number1CrateTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.IGNITED_CHICA.get(), context -> new IgnitedChicaTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.MOLTEN_SIT.get(), context -> new MoltenSitTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FREDDY_FAZ_BEAR.get(), context -> new FreddyFazBearTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.MIDNIGHT_MOTORIST.get(), context -> new MidnightMotoristTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FRUITY_MAZE.get(), context -> new FruityMazeTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.STEPHAN_PLUSH.get(), context -> new StephanPlushTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PAN_STAN.get(), context -> new PanStanTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BUCKET_BOB.get(), context -> new BucketBobTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.MR_CAN_DO.get(), context -> new MrCanDoTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BALLOON_BOY.get(), context -> new BalloonBoyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BON_BON.get(), context -> new BonBonTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BONNET.get(), context -> new BonnetTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BONNIE.get(), context -> new BonnieTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.CHICA.get(), context -> new ChicaTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FOXY.get(), context -> new FoxyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FT_FOXY.get(), context -> new FtFoxyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LOL_BIT.get(), context -> new LolBitTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LOL_BIT_DT.get(), context -> new LolBitDtTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.RETRO_CHICA.get(), context -> new RetroChicaTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.TOY_FREDDY.get(), context -> new ToyFreddyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.TOY_FOXY.get(), context -> new ToyFoxyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.TOY_CHICA.get(), context -> new ToyChicaTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.TOY_BONNIE.get(), context -> new ToyBonnieTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BONK_A_BON.get(), context -> new BonkABonTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BROKEN_FREDDY.get(), context -> new BrokenFreddyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BROKEN_BONNIE.get(), context -> new BrokenBonnieTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BROKEN_CHICA.get(), context -> new BrokenChicaTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.CARNIVAL_HOOPS.get(), context -> new CarnivalHoopsTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.GRAVITY_VORTEX.get(), context -> new GravityVortexTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.GRAVITY_VORTEX_2.get(), context -> new GravityVortex2TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PICKLES.get(), context -> new PicklesTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.DOUG_THE_DOG.get(), context -> new DougTheDogTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.WITHERED_DOUG_THE_DOG.get(), context -> new WitheredDougTheDogTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ENDO_02.get(), context -> new Endo02TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.DISCOUNT_COOLING_UNIT.get(), context -> new DiscountCoolingUnitTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.RASC.get(), context -> new RascTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SHRED_BEAR.get(), context -> new ShredBearTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LOL_BIT_409.get(), context -> new LolBit409TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BALLOON_CART.get(), context -> new BalloonCartTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.RIDING_ROCKETS_RED.get(), context -> new RidingRocketsRedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.RIDING_ROCKETS_PURPLE.get(), context -> new RidingRocketsPurpleTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PAPER_PLATES.get(), context -> new PaperPlatesTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_STAGE_LIGHT_GREEN.get(), context -> new NeonStageLightGreenTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_STAGE_LIGHTS_PINK.get(), context -> new NeonStageLightsPinkTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_STAGE_LIGHTS_BLUE.get(), context -> new NeonStageLightsBlueTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.CEILING_STAGE_LIGHTS.get(), context -> new CeilingStageLightsTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.CEILING_STAGE_LIGHTPINK.get(), context -> new CeilingStageLightpinkTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.CEILING_STAGE_LIGHTBLUE.get(), context -> new CeilingStageLightblueTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.DELUXE_BALLPIT.get(), context -> new DeluxeBallpitTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ROTTEN_PIT.get(), context -> new RottenPitTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FRIGHTS_SIGN.get(), context -> new FrightsSignTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FRIGHTS_SIGN_2.get(), context -> new FrightsSign2TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIZZA_PLACE_SIGN.get(), context -> new PizzaPlaceSignTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIZZA_PLACE_SIGN_OLD.get(), context -> new PizzaPlaceSignOldTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.HAZY_REINDEER.get(), context -> new HazyReindeerTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.HAZY_REINDEER_ANIMATED.get(), context -> new HazyReindeerAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.WALLY_WALRUS.get(), context -> new WallyWalrusTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.WALLY_WALRUS_ANIMATED.get(), context -> new WallyWalrusAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PUFFY_PUFFINS.get(), context -> new PuffyPuffinsTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PUFFY_PUFFINS_ANIMATED.get(), context -> new PuffyPuffinsAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.WITHERED_WALLY_WALRUS.get(), context -> new WitheredWallyWalrusTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.WITHERED_PUFFY_PUFFINS.get(), context -> new WitheredPuffyPuffinsTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.WITHERED_HAZY_REINDEER.get(), context -> new WitheredHazyReindeerTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.GT_ENDO.get(), context -> new GtEndoTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.GT_ENDO_ANIMATED.get(), context -> new GtEndoAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ST_ENDO.get(), context -> new StEndoTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ST_ENDO_ANIMATED.get(), context -> new StEndoAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BUFFET_ENDO.get(), context -> new BuffetEndoTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.JEFFS_PIZZA_SIGN.get(), context -> new JeffsPizzaSignTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.LOLBIT_RECORD.get(), context -> new LolbitRecordTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.COIN.get(), context -> new CoinTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.COINS_5.get(), context -> new Coins5TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.COINS_100.get(), context -> new Coins25TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.COINS_25.get(), context -> new Coins100TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.COINS_1000.get(), context -> new Coins1000TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.COINS_10000.get(), context -> new Coins10000TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.MEGAULTIMATESPEAKERTRON_3000.get(), context -> new Megaultimatespeakertron3000TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.HEAVY_DUITY_DOOR.get(), context -> new HeavyDuityDoorTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.HEAVY_DUITY_DOOR_CLOSED.get(), context -> new HeavyDuityDoorClosedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SIGN_DDW.get(), context -> new SignDDWTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SIGN_SBT.get(), context -> new SignSBTTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SIGN_RFA.get(), context -> new SignRFATileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.RETRO_CHICA_ANIMATED.get(), context -> new RetroChicaAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SIGN_SNS.get(), context -> new SignSNSTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.JOLLY_THE_RAT.get(), context -> new JollyTheRatTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.JOLLY_THE_RAT_ANIMATED.get(), context -> new JollyTheRatAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SALVAGED_JOLLY.get(), context -> new SalvagedJollyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_STAGE_LIGHTS_ORANGE.get(), context -> new NeonStageLightsOrangeTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.CEILING_STAGE_LIGHT_ORANGE.get(), context -> new CeilingStageLightOrangeTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SIGN_MS.get(), context -> new SignMSTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIZZA_BOX_85_OPEN.get(), context -> new PizzaBox85OpenTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIZZA_BOX_85_CLOSED.get(), context -> new PizzaBox85ClosedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIZZA_BOX_87_OPEN.get(), context -> new PizzaBox87OpenTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIZZA_BOX_87_CLOSED.get(), context -> new PizzaBox87ClosedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIZZA_BOX_93_OPEN.get(), context -> new PizzaBox93OpenTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIZZA_BOX_93_CLOSED.get(), context -> new PizzaBox93ClosedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIZZA_BOX_24_OPEN.get(), context -> new PizzaBox24OpenTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PIZZA_BOX_24_CLOSED.get(), context -> new PizzaBox24ClosedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.DOUG_THE_DOG_ANIMATED.get(), context -> new DougTheDogAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PROJECTOR.get(), context -> new ProjectorTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.CAM.get(), context -> new CamTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FREDDY_CUT_OUT.get(), context -> new FreddyCutOutTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.BONNIE_CUT_OUT.get(), context -> new BonnieCutOutTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.CHICA_CUT_OUT.get(), context -> new ChicaCutOutTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.HELPY_CUT_OUT.get(), context -> new HelpyCutOutTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PROJECTION.get(), context -> new ProjectionTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_JUKE_BOX_OFF.get(), context -> new NeonJukeBoxOffTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.GUS_THE_PUG.get(), context -> new GusThePugTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PINBALL_TOY_FREDDY.get(), context -> new PinballToyFreddyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.GUS_THE_PUG_ANIMATED.get(), context -> new GusThePugAnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PC.get(), context -> new PCTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FREDBEAR_01.get(), context -> new Fredbear01TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FREDBEAR_01_ANIMATED.get(), context -> new Fredbear01AnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SPRINGBONNIE_01.get(), context -> new Springbonnie01TileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.SPRINGBONNIE_01_ANIMATED.get(), context -> new Springbonnie01AnimatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.TOY_PUG.get(), context -> new ToyPugTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PRIZE_COUNTER_SIGN.get(), context -> new PrizeCounterSignTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.REST_ROOM_SIGN.get(), context -> new RestRoomSignTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.ARCADE_SIGN.get(), context -> new ArcadeSignTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.PARTY_ROOM_SIGN.get(), context -> new PartyRoomSignTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.KITCHEN_SIGN.get(), context -> new KitchenSignTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_RED_LIGHT_STRIP.get(), context -> new NeonRedLightStripTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_RED_LIGHT_STRIP_RIGHT.get(), context -> new NeonRedLightStripRightTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_RED_LIGHT_STRIP_LEFT.get(), context -> new NeonRedLightStripLeftTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_GREEN_LIGHT_STRIP.get(), context -> new NeonGreenLightStripTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_GREEN_LIGHT_STRIP_RIGHT.get(), context -> new NeonGreenLightStripRightTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_GREEN_LIGHT_STRIP_LEFT.get(), context -> new NeonGreenLightStripLeftTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_BLUE_LIGHT_STRIP.get(), context -> new NeonBlueLightStripTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_BLUE_LIGHT_STRIP_RIGHT.get(), context -> new NeonBlueLightStripRightTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_BLUE_LIGHT_STRIP_LEFT.get(), context -> new NeonBlueLightStripLeftTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_YELLOW_LIGHT_STRIP.get(), context -> new NeonYellowLightStripTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_YELLOW_LIGHT_STRIP_RIGHT.get(), context -> new NeonYellowLightStripRightTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_YELLOW_LIGHT_STRIP_LEFT.get(), context -> new NeonYellowLightStripLeftTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_ORANGE_LIGHT_STRIP.get(), context -> new NeonOrangeLightStripTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_ORANGE_LIGHT_STRIP_RIGHT.get(), context -> new NeonOrangeLightStripRightTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.NEON_ORANGE_LIGHT_LEFT.get(), context -> new NeonOrangeLightLeftTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FT_FREDDY.get(), context -> new FtFreddyTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FRED_BEAR.get(), context -> new FredBearTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.FREDBEAR_DEACTIVATED.get(), context -> new FredbearDeactivatedTileRenderer());
		event.registerBlockEntityRenderer(FbmsModBlockEntities.INDIGO.get(), context -> new IndigoTileRenderer());
	}
}
