
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fbms.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.fbms.block.YellowWallsBlock;
import net.mcreator.fbms.block.YellowStageBricksBlock;
import net.mcreator.fbms.block.YellowCurtainBlock;
import net.mcreator.fbms.block.WitheredWallyWalrusBlock;
import net.mcreator.fbms.block.WitheredPuffyPuffinsBlock;
import net.mcreator.fbms.block.WitheredHazyReindeerBlock;
import net.mcreator.fbms.block.WitheredDougTheDogBlock;
import net.mcreator.fbms.block.WinkSignBlock;
import net.mcreator.fbms.block.WhiteWallBlock;
import net.mcreator.fbms.block.WhiteStageBricksBlock;
import net.mcreator.fbms.block.WhiteStaffDoorBlock;
import net.mcreator.fbms.block.WhiteCurtainBlock;
import net.mcreator.fbms.block.WallyWalrusBlock;
import net.mcreator.fbms.block.WallyWalrusAnimatedBlock;
import net.mcreator.fbms.block.VESSELBlock;
import net.mcreator.fbms.block.ToyFreddyBlock;
import net.mcreator.fbms.block.ToyFoxyBlock;
import net.mcreator.fbms.block.ToyChicaBlock;
import net.mcreator.fbms.block.ToyBonnieBlock;
import net.mcreator.fbms.block.ThinYellowCurtainBlock;
import net.mcreator.fbms.block.ThinWhiteCurtainBlock;
import net.mcreator.fbms.block.ThinRedCurtainBlock;
import net.mcreator.fbms.block.ThinPurpleCurtainBlock;
import net.mcreator.fbms.block.ThinPinkCurtainBlock;
import net.mcreator.fbms.block.ThinOrangeCurtainBlock;
import net.mcreator.fbms.block.ThinMagentaCurtainBlock;
import net.mcreator.fbms.block.ThinLimeCurtainBlock;
import net.mcreator.fbms.block.ThinLightGrayCurtainBlock;
import net.mcreator.fbms.block.ThinLightBlueCurtainBlock;
import net.mcreator.fbms.block.ThinGreenCurtainBlock;
import net.mcreator.fbms.block.ThinGrayCurtainBlock;
import net.mcreator.fbms.block.ThinCyanCurtainBlock;
import net.mcreator.fbms.block.ThinBrownCurtainBlock;
import net.mcreator.fbms.block.ThinBlueCurtainBlock;
import net.mcreator.fbms.block.ThinBlackCurtainBlock;
import net.mcreator.fbms.block.TheMangleBlock;
import net.mcreator.fbms.block.TVWackyWartPasteBlock;
import net.mcreator.fbms.block.TVScreamBlock;
import net.mcreator.fbms.block.TVPeppersPickledPopcornBlock;
import net.mcreator.fbms.block.TVOffBlock;
import net.mcreator.fbms.block.TVNewsBlock;
import net.mcreator.fbms.block.TVMartiesPlungersBlock;
import net.mcreator.fbms.block.TVMarceloBlock;
import net.mcreator.fbms.block.TVLalliesLolliesBlock;
import net.mcreator.fbms.block.TVKillerKlownsBlock;
import net.mcreator.fbms.block.TVJawsBlock;
import net.mcreator.fbms.block.TVIatrBlock;
import net.mcreator.fbms.block.TVHemanBlock;
import net.mcreator.fbms.block.TVGarfieldShowBlock;
import net.mcreator.fbms.block.TVFreddyAndFriendsBlock;
import net.mcreator.fbms.block.TVFlosGlossyFlossBlock;
import net.mcreator.fbms.block.TVFiztimePopSodaBlock;
import net.mcreator.fbms.block.TVDougBlock;
import net.mcreator.fbms.block.StreamerFiztimeBlock;
import net.mcreator.fbms.block.StephanPlushBlock;
import net.mcreator.fbms.block.StationWagonBlockBlock;
import net.mcreator.fbms.block.StarArchBlock;
import net.mcreator.fbms.block.StallDoorBlock;
import net.mcreator.fbms.block.StaffDoorBlock;
import net.mcreator.fbms.block.StEndoBlock;
import net.mcreator.fbms.block.StEndoAnimatedBlock;
import net.mcreator.fbms.block.SpringBonniePosterBlock;
import net.mcreator.fbms.block.SignSNSBlock;
import net.mcreator.fbms.block.SignSBTBlock;
import net.mcreator.fbms.block.SignRFABlock;
import net.mcreator.fbms.block.SignMSBlock;
import net.mcreator.fbms.block.SignDDWBlock;
import net.mcreator.fbms.block.ShredBearBlock;
import net.mcreator.fbms.block.SecurityPuppetBlock;
import net.mcreator.fbms.block.ScrapTrapBlock;
import net.mcreator.fbms.block.ScrapStageBlockStairsBlock;
import net.mcreator.fbms.block.ScrapStageBlockSlabBlock;
import net.mcreator.fbms.block.ScrapStageBlockBlock;
import net.mcreator.fbms.block.SanitationStationBlock;
import net.mcreator.fbms.block.SalvagedJollyBlock;
import net.mcreator.fbms.block.SafetyPosterFreddyBlock;
import net.mcreator.fbms.block.SafetyPosterFoxyBlock;
import net.mcreator.fbms.block.SafetyPosterChicaBlock;
import net.mcreator.fbms.block.SafetyPosterBonnieBlock;
import net.mcreator.fbms.block.SafetyPosterBlock;
import net.mcreator.fbms.block.RustyBlock;
import net.mcreator.fbms.block.RustyAnimatedBlock;
import net.mcreator.fbms.block.RottenPitBlock;
import net.mcreator.fbms.block.RoseyBlock;
import net.mcreator.fbms.block.RockStarFreddyBlock;
import net.mcreator.fbms.block.RockStarFreddyAnimatedBlock;
import net.mcreator.fbms.block.RockStarFoxyBlock;
import net.mcreator.fbms.block.RockStarFoxyAnimatedBlock;
import net.mcreator.fbms.block.RockStarChicaBlock;
import net.mcreator.fbms.block.RockStarChicaAnimatedBlock;
import net.mcreator.fbms.block.RockStarBonnieBlock;
import net.mcreator.fbms.block.RockStarBonnieAnimatedBlock;
import net.mcreator.fbms.block.RidingRocketsRedBlock;
import net.mcreator.fbms.block.RidingRocketsPurpleBlock;
import net.mcreator.fbms.block.RetroChicaBlock;
import net.mcreator.fbms.block.RetroChicaAnimatedBlock;
import net.mcreator.fbms.block.RedWhiteTilesStairsBlock;
import net.mcreator.fbms.block.RedWhiteTilesSlabBlock;
import net.mcreator.fbms.block.RedWhiteTilesBlock;
import net.mcreator.fbms.block.RedWallTopBlock;
import net.mcreator.fbms.block.RedWallBlock;
import net.mcreator.fbms.block.RedStageBricksBlock;
import net.mcreator.fbms.block.RedStageBlockBlock;
import net.mcreator.fbms.block.RedCurtainBlock;
import net.mcreator.fbms.block.RedBlueTilesStairsBlock;
import net.mcreator.fbms.block.RedBlueTilesSlabBlock;
import net.mcreator.fbms.block.RedBlueTilesBlock;
import net.mcreator.fbms.block.RbonniePosterBlock;
import net.mcreator.fbms.block.RascBlock;
import net.mcreator.fbms.block.RFreddyPosterBlock;
import net.mcreator.fbms.block.RFoxyPosterBlock;
import net.mcreator.fbms.block.RChicaPosterBlock;
import net.mcreator.fbms.block.PurpleWallBlock;
import net.mcreator.fbms.block.PurpleStageBricksBlock;
import net.mcreator.fbms.block.PurpleStageBlockBlock;
import net.mcreator.fbms.block.PurpleCurtainBlock;
import net.mcreator.fbms.block.PuppetBoxBlock;
import net.mcreator.fbms.block.PuffyPuffinsBlock;
import net.mcreator.fbms.block.PuffyPuffinsAnimatedBlock;
import net.mcreator.fbms.block.ProjectorBlock;
import net.mcreator.fbms.block.ProjectionBlock;
import net.mcreator.fbms.block.PrizeKingBlock;
import net.mcreator.fbms.block.PoshWallTilesBlock;
import net.mcreator.fbms.block.PizzaPlaceSignOldBlock;
import net.mcreator.fbms.block.PizzaPlaceSignBlock;
import net.mcreator.fbms.block.PizzaBox93OpenBlock;
import net.mcreator.fbms.block.PizzaBox93ClosedBlock;
import net.mcreator.fbms.block.PizzaBox87OpenBlock;
import net.mcreator.fbms.block.PizzaBox87ClosedBlock;
import net.mcreator.fbms.block.PizzaBox85OpenBlock;
import net.mcreator.fbms.block.PizzaBox85ClosedBlock;
import net.mcreator.fbms.block.PizzaBox24OpenBlock;
import net.mcreator.fbms.block.PizzaBox24ClosedBlock;
import net.mcreator.fbms.block.PinkWallBlock;
import net.mcreator.fbms.block.PinkStageBricksBlock;
import net.mcreator.fbms.block.PinkCurtainBlock;
import net.mcreator.fbms.block.PinballToyFreddyBlock;
import net.mcreator.fbms.block.PinTheBowtieOnTheTieTheToyFreddyBlock;
import net.mcreator.fbms.block.PinTheBowtieOnTheFreddyBlock;
import net.mcreator.fbms.block.PigPatchBlock;
import net.mcreator.fbms.block.PigPatchAnimatedBlock;
import net.mcreator.fbms.block.PicklesBlock;
import net.mcreator.fbms.block.PapperPalOrvilBlock;
import net.mcreator.fbms.block.PapperPalMrHippoBlock;
import net.mcreator.fbms.block.PaperPlatesBlock;
import net.mcreator.fbms.block.PaperPalClownBlock;
import net.mcreator.fbms.block.PanStanBlock;
import net.mcreator.fbms.block.OrvilleBlock;
import net.mcreator.fbms.block.OrvilleAnimatedBlock;
import net.mcreator.fbms.block.OrangeWallBlock;
import net.mcreator.fbms.block.OrangeStageBricksBlock;
import net.mcreator.fbms.block.OrangeCurtainBlock;
import net.mcreator.fbms.block.OldFreddyBlock;
import net.mcreator.fbms.block.OldFoxyBlock;
import net.mcreator.fbms.block.OldChicaBlock;
import net.mcreator.fbms.block.OldBonnieBlock;
import net.mcreator.fbms.block.Number1CrateBlock;
import net.mcreator.fbms.block.NoveltyTrafficLightBlock;
import net.mcreator.fbms.block.NeonStageLightsPinkBlock;
import net.mcreator.fbms.block.NeonStageLightsOrangeBlock;
import net.mcreator.fbms.block.NeonStageLightsBlueBlock;
import net.mcreator.fbms.block.NeonStageLightGreenBlock;
import net.mcreator.fbms.block.NeonPartySet4Block;
import net.mcreator.fbms.block.NeonPartySet3Block;
import net.mcreator.fbms.block.NeonPartySet2Block;
import net.mcreator.fbms.block.NeonPartySet1Block;
import net.mcreator.fbms.block.NeonJukeBoxOffBlock;
import net.mcreator.fbms.block.NeonJukeBoxBlock;
import net.mcreator.fbms.block.NeddBearBlock;
import net.mcreator.fbms.block.NeddBearAnimatedBlock;
import net.mcreator.fbms.block.MusicManBlock;
import net.mcreator.fbms.block.MusicManAnimatedBlock;
import net.mcreator.fbms.block.MrHugsBlock;
import net.mcreator.fbms.block.MrHippoBlock;
import net.mcreator.fbms.block.MrHippoAnimatedBlock;
import net.mcreator.fbms.block.MrCanDoBlock;
import net.mcreator.fbms.block.MonitorWorkBlock;
import net.mcreator.fbms.block.MonitorStephanBlock;
import net.mcreator.fbms.block.MonitorScai8Block;
import net.mcreator.fbms.block.MonitorScai7Block;
import net.mcreator.fbms.block.MonitorScai6Block;
import net.mcreator.fbms.block.MonitorScai5Block;
import net.mcreator.fbms.block.MonitorScai4Block;
import net.mcreator.fbms.block.MonitorScai3Block;
import net.mcreator.fbms.block.MonitorScai2Block;
import net.mcreator.fbms.block.MonitorScai1Block;
import net.mcreator.fbms.block.MonitorOffBlock;
import net.mcreator.fbms.block.MonitorLolbitBlock;
import net.mcreator.fbms.block.MonitorBluescreenBlock;
import net.mcreator.fbms.block.MoltenSitBlock;
import net.mcreator.fbms.block.MoltenFreddyBlock;
import net.mcreator.fbms.block.MoldyRabbitBlock;
import net.mcreator.fbms.block.MidnightMotoristBlock;
import net.mcreator.fbms.block.Megaultimatespeakertron3000Block;
import net.mcreator.fbms.block.MagentaWallBlock;
import net.mcreator.fbms.block.MagentaStageBricksBlock;
import net.mcreator.fbms.block.MagentaCurtainBlock;
import net.mcreator.fbms.block.LolbitRecordBlock;
import net.mcreator.fbms.block.LolBitDtBlock;
import net.mcreator.fbms.block.LolBitBlock;
import net.mcreator.fbms.block.LolBit409Block;
import net.mcreator.fbms.block.LimeWallBlock;
import net.mcreator.fbms.block.LimeCurtainBlock;
import net.mcreator.fbms.block.LimeBricksBlock;
import net.mcreator.fbms.block.LightGrayCurtainBlock;
import net.mcreator.fbms.block.LightGrayBricksBlock;
import net.mcreator.fbms.block.LightBlueWallBlock;
import net.mcreator.fbms.block.LightBlueCurtainBlock;
import net.mcreator.fbms.block.LemonadeClownBlock;
import net.mcreator.fbms.block.LeftyPosterBlock;
import net.mcreator.fbms.block.LeftyBlock;
import net.mcreator.fbms.block.LeftyAnimatedBlock;
import net.mcreator.fbms.block.LargeSignBlock;
import net.mcreator.fbms.block.LargeSign4Block;
import net.mcreator.fbms.block.LargeSign3Block;
import net.mcreator.fbms.block.LargeSign2Block;
import net.mcreator.fbms.block.LargeBlackWhiteTilesBlock;
import net.mcreator.fbms.block.LadderTowerBlock;
import net.mcreator.fbms.block.JollyTheRatBlock;
import net.mcreator.fbms.block.JollyTheRatAnimatedBlock;
import net.mcreator.fbms.block.JeffsPizzaSignBlock;
import net.mcreator.fbms.block.ImpalaBlockBlock;
import net.mcreator.fbms.block.IgnitedChicaBlock;
import net.mcreator.fbms.block.HelpyCutOutBlock;
import net.mcreator.fbms.block.HeavyDuityDoorClosedBlock;
import net.mcreator.fbms.block.HeavyDuityDoorBlock;
import net.mcreator.fbms.block.HazyReindeerBlock;
import net.mcreator.fbms.block.HazyReindeerAnimatedBlock;
import net.mcreator.fbms.block.HappyFrogBlock;
import net.mcreator.fbms.block.HappYFrogAnimatedBlock;
import net.mcreator.fbms.block.GusThePugBlock;
import net.mcreator.fbms.block.GusThePugAnimatedBlock;
import net.mcreator.fbms.block.GumballSwivelHandsBlock;
import net.mcreator.fbms.block.GtEndoBlock;
import net.mcreator.fbms.block.GtEndoAnimatedBlock;
import net.mcreator.fbms.block.GreenWallBlock;
import net.mcreator.fbms.block.GreenStageBricksBlock;
import net.mcreator.fbms.block.GreenCurtainBlock;
import net.mcreator.fbms.block.GrayWallBlock;
import net.mcreator.fbms.block.GrayStageBricksBlock;
import net.mcreator.fbms.block.GrayCurtainBlock;
import net.mcreator.fbms.block.GravityVortexBlock;
import net.mcreator.fbms.block.GravityVortex2Block;
import net.mcreator.fbms.block.GlassOfficeDoorTextBlock;
import net.mcreator.fbms.block.GlassOfficeDoorBlock;
import net.mcreator.fbms.block.GlassDoorBlock;
import net.mcreator.fbms.block.GarfPlushBlock;
import net.mcreator.fbms.block.FuntimeDelilahblockBlock;
import net.mcreator.fbms.block.FuntimeDelilahBlock;
import net.mcreator.fbms.block.FuntimeChicaAnimatedBlock;
import net.mcreator.fbms.block.FunTimeChicaBlock;
import net.mcreator.fbms.block.FullWhiteTilesStairsBlock;
import net.mcreator.fbms.block.FullWhiteTilesSlabBlock;
import net.mcreator.fbms.block.FullWhiteTilesBlock;
import net.mcreator.fbms.block.FullBlackTilesStairsBlock;
import net.mcreator.fbms.block.FullBlackTilesSlabBlock;
import net.mcreator.fbms.block.FullBlackTilesBlock;
import net.mcreator.fbms.block.FtFoxyBlock;
import net.mcreator.fbms.block.FruityMazeBlock;
import net.mcreator.fbms.block.FruitPunchClownBlock;
import net.mcreator.fbms.block.FrightsSignBlock;
import net.mcreator.fbms.block.FrightsSign2Block;
import net.mcreator.fbms.block.FreddyFazBearBlock;
import net.mcreator.fbms.block.FreddyCutOutBlock;
import net.mcreator.fbms.block.FredbearMuralBlock;
import net.mcreator.fbms.block.FredBearPosterBlock;
import net.mcreator.fbms.block.FredBearPizzaPosterBlock;
import net.mcreator.fbms.block.FoxyBlock;
import net.mcreator.fbms.block.FoilPartySet4Block;
import net.mcreator.fbms.block.FoilPartySet3Block;
import net.mcreator.fbms.block.FoilPartySet2Block;
import net.mcreator.fbms.block.FoilPartySet1Block;
import net.mcreator.fbms.block.EnhancedSpeakerSetBlock;
import net.mcreator.fbms.block.Endo02Block;
import net.mcreator.fbms.block.Endo01Block;
import net.mcreator.fbms.block.Endo01AnimatedBlock;
import net.mcreator.fbms.block.ElChipBlock;
import net.mcreator.fbms.block.ElChipAnimatedBlock;
import net.mcreator.fbms.block.EggBabyBlock;
import net.mcreator.fbms.block.DuckPondBlock;
import net.mcreator.fbms.block.DrTeathBlock;
import net.mcreator.fbms.block.DougTheDogBlock;
import net.mcreator.fbms.block.DougTheDogAnimatedBlock;
import net.mcreator.fbms.block.DollsBlock;
import net.mcreator.fbms.block.DogeRamBlockBlock;
import net.mcreator.fbms.block.DocPlushBlock;
import net.mcreator.fbms.block.DiscountCoolingUnitBlock;
import net.mcreator.fbms.block.DiscountBallpitBlock;
import net.mcreator.fbms.block.DiscoPizzaBlock;
import net.mcreator.fbms.block.DeluxeSpeakerSetBlock;
import net.mcreator.fbms.block.DeluxeBallpitBlock;
import net.mcreator.fbms.block.DarkGrayWallBlock;
import net.mcreator.fbms.block.DBalloonBoyBlock;
import net.mcreator.fbms.block.CyanWallBlock;
import net.mcreator.fbms.block.CyanStageBricksBlock;
import net.mcreator.fbms.block.CyanCurtainBlock;
import net.mcreator.fbms.block.Coins5Block;
import net.mcreator.fbms.block.Coins25Block;
import net.mcreator.fbms.block.Coins100Block;
import net.mcreator.fbms.block.Coins1000Block;
import net.mcreator.fbms.block.Coins10000Block;
import net.mcreator.fbms.block.CoinBlock;
import net.mcreator.fbms.block.ChicaOLanternBlock;
import net.mcreator.fbms.block.ChicaCutOutBlock;
import net.mcreator.fbms.block.ChicaBlock;
import net.mcreator.fbms.block.CelebratePosterBlock;
import net.mcreator.fbms.block.CeilingTilesBlock;
import net.mcreator.fbms.block.CeilingStageLightsBlock;
import net.mcreator.fbms.block.CeilingStageLightpinkBlock;
import net.mcreator.fbms.block.CeilingStageLightblueBlock;
import net.mcreator.fbms.block.CeilingStageLightOrangeBlock;
import net.mcreator.fbms.block.CeilingLightOnBlock;
import net.mcreator.fbms.block.CeilingLightBlock;
import net.mcreator.fbms.block.CarnivalHoopsBlock;
import net.mcreator.fbms.block.CandyCadetBlock;
import net.mcreator.fbms.block.CamBlock;
import net.mcreator.fbms.block.BuffetEndoBlock;
import net.mcreator.fbms.block.BucketBobBlock;
import net.mcreator.fbms.block.BrownStageBricksBlock;
import net.mcreator.fbms.block.BrownCurtainBlock;
import net.mcreator.fbms.block.BrokenFreddyBlock;
import net.mcreator.fbms.block.BrokenChicaBlock;
import net.mcreator.fbms.block.BrokenBonnieBlock;
import net.mcreator.fbms.block.BrokenBarryPolarAnimatedBlock;
import net.mcreator.fbms.block.BrandedBoxBlock;
import net.mcreator.fbms.block.BoxBlock;
import net.mcreator.fbms.block.BonnieCutOutBlock;
import net.mcreator.fbms.block.BonnieBlock;
import net.mcreator.fbms.block.BonnetBlock;
import net.mcreator.fbms.block.BonkABonBlock;
import net.mcreator.fbms.block.BonBonBlock;
import net.mcreator.fbms.block.BlueWhiteTilesStairsBlock;
import net.mcreator.fbms.block.BlueWhiteTilesSlabBlock;
import net.mcreator.fbms.block.BlueWhiteTilesBlock;
import net.mcreator.fbms.block.BlueWallBlock;
import net.mcreator.fbms.block.BlueStageBricksBlock;
import net.mcreator.fbms.block.BlueCurtainBlock;
import net.mcreator.fbms.block.BlankStaffDoorBlock;
import net.mcreator.fbms.block.BlackWhiteTilesStairsBlock;
import net.mcreator.fbms.block.BlackWhiteTilesSlabBlock;
import net.mcreator.fbms.block.BlackWhiteTilesBlock;
import net.mcreator.fbms.block.BlackWhiteConfettiTilesBlock;
import net.mcreator.fbms.block.BlackWhiteConfettiTileStairsBlock;
import net.mcreator.fbms.block.BlackWhiteConfettiTileSlabBlock;
import net.mcreator.fbms.block.BlackWhiteCleanTilesBlock;
import net.mcreator.fbms.block.BlackWhiteCleanTileStairsBlock;
import net.mcreator.fbms.block.BlackWhiteCleanTileSlabBlock;
import net.mcreator.fbms.block.BlackWallBlock;
import net.mcreator.fbms.block.BlackStageBricksBlock;
import net.mcreator.fbms.block.BlackRedTilesStairsBlock;
import net.mcreator.fbms.block.BlackRedTilesSlabBlock;
import net.mcreator.fbms.block.BlackRedTilesBlock;
import net.mcreator.fbms.block.BlackCurtainBlock;
import net.mcreator.fbms.block.BlackBlueTilesStairsBlock;
import net.mcreator.fbms.block.BlackBlueTilesSlabBlock;
import net.mcreator.fbms.block.BlackBlueTilesBlock;
import net.mcreator.fbms.block.BiteFredBearCutoutBlock;
import net.mcreator.fbms.block.BasicStageBlockStairsBlock;
import net.mcreator.fbms.block.BasicStageBlockSlabBlock;
import net.mcreator.fbms.block.BarryPolarFixedBlock;
import net.mcreator.fbms.block.BarryPolarBlock;
import net.mcreator.fbms.block.BarryPolarAnimatedBlock;
import net.mcreator.fbms.block.BalloonCartBlock;
import net.mcreator.fbms.block.BalloonBoyBlock;
import net.mcreator.fbms.block.BalloonBarrelBlock;
import net.mcreator.fbms.block.BallPitTowerBlock;
import net.mcreator.fbms.block.BaggyMaggieBlock;
import net.mcreator.fbms.block.ArcadeFreddyOnBlock;
import net.mcreator.fbms.block.ArcadeFreddyBlock;
import net.mcreator.fbms.block.ArcadeFoxyOnBlock;
import net.mcreator.fbms.block.ArcadeFoxyBlock;
import net.mcreator.fbms.block.ArcadeBonnieOnBlock;
import net.mcreator.fbms.block.ArcadeBonnieBlock;
import net.mcreator.fbms.FbmsMod;

public class FbmsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, FbmsMod.MODID);
	public static final RegistryObject<Block> BLACK_WHITE_CLEAN_TILES = REGISTRY.register("black_white_clean_tiles", () -> new BlackWhiteCleanTilesBlock());
	public static final RegistryObject<Block> BLACK_WHITE_CLEAN_TILE_STAIRS = REGISTRY.register("black_white_clean_tile_stairs", () -> new BlackWhiteCleanTileStairsBlock());
	public static final RegistryObject<Block> BLACK_WHITE_CLEAN_TILE_SLAB = REGISTRY.register("black_white_clean_tile_slab", () -> new BlackWhiteCleanTileSlabBlock());
	public static final RegistryObject<Block> BLACK_WHITE_CONFETTI_TILES = REGISTRY.register("black_white_confetti_tiles", () -> new BlackWhiteConfettiTilesBlock());
	public static final RegistryObject<Block> BLACK_WHITE_CONFETTI_TILE_STAIRS = REGISTRY.register("black_white_confetti_tile_stairs", () -> new BlackWhiteConfettiTileStairsBlock());
	public static final RegistryObject<Block> BLACK_WHITE_CONFETTI_TILE_SLAB = REGISTRY.register("black_white_confetti_tile_slab", () -> new BlackWhiteConfettiTileSlabBlock());
	public static final RegistryObject<Block> DISCO_PIZZA = REGISTRY.register("disco_pizza", () -> new DiscoPizzaBlock());
	public static final RegistryObject<Block> SCRAP_STAGE_BLOCK = REGISTRY.register("scrap_stage_block", () -> new ScrapStageBlockBlock());
	public static final RegistryObject<Block> SCRAP_STAGE_BLOCK_STAIRS = REGISTRY.register("scrap_stage_block_stairs", () -> new ScrapStageBlockStairsBlock());
	public static final RegistryObject<Block> SCRAP_STAGE_BLOCK_SLAB = REGISTRY.register("scrap_stage_block_slab", () -> new ScrapStageBlockSlabBlock());
	public static final RegistryObject<Block> RED_STAGE_BLOCK = REGISTRY.register("red_stage_block", () -> new RedStageBlockBlock());
	public static final RegistryObject<Block> PURPLE_STAGE_BLOCK = REGISTRY.register("purple_stage_block", () -> new PurpleStageBlockBlock());
	public static final RegistryObject<Block> BASIC_STAGE_BLOCK_STAIRS = REGISTRY.register("basic_stage_block_stairs", () -> new BasicStageBlockStairsBlock());
	public static final RegistryObject<Block> BASIC_STAGE_BLOCK_SLAB = REGISTRY.register("basic_stage_block_slab", () -> new BasicStageBlockSlabBlock());
	public static final RegistryObject<Block> STAR_ARCH = REGISTRY.register("star_arch", () -> new StarArchBlock());
	public static final RegistryObject<Block> PAPER_PAL_CLOWN = REGISTRY.register("paper_pal_clown", () -> new PaperPalClownBlock());
	public static final RegistryObject<Block> PAPPER_PAL_MR_HIPPO = REGISTRY.register("papper_pal_mr_hippo", () -> new PapperPalMrHippoBlock());
	public static final RegistryObject<Block> PAPPER_PAL_ORVIL = REGISTRY.register("papper_pal_orvil", () -> new PapperPalOrvilBlock());
	public static final RegistryObject<Block> GUMBALL_SWIVEL_HANDS = REGISTRY.register("gumball_swivel_hands", () -> new GumballSwivelHandsBlock());
	public static final RegistryObject<Block> LEMONADE_CLOWN = REGISTRY.register("lemonade_clown", () -> new LemonadeClownBlock());
	public static final RegistryObject<Block> FRUIT_PUNCH_CLOWN = REGISTRY.register("fruit_punch_clown", () -> new FruitPunchClownBlock());
	public static final RegistryObject<Block> BALLOON_BARREL = REGISTRY.register("balloon_barrel", () -> new BalloonBarrelBlock());
	public static final RegistryObject<Block> MIDNIGHT_MOTORIST = REGISTRY.register("midnight_motorist", () -> new MidnightMotoristBlock());
	public static final RegistryObject<Block> FRUITY_MAZE = REGISTRY.register("fruity_maze", () -> new FruityMazeBlock());
	public static final RegistryObject<Block> DISCOUNT_BALLPIT = REGISTRY.register("discount_ballpit", () -> new DiscountBallpitBlock());
	public static final RegistryObject<Block> BALL_PIT_TOWER = REGISTRY.register("ball_pit_tower", () -> new BallPitTowerBlock());
	public static final RegistryObject<Block> DELUXE_BALLPIT = REGISTRY.register("deluxe_ballpit", () -> new DeluxeBallpitBlock());
	public static final RegistryObject<Block> DUCK_POND = REGISTRY.register("duck_pond", () -> new DuckPondBlock());
	public static final RegistryObject<Block> SANITATION_STATION = REGISTRY.register("sanitation_station", () -> new SanitationStationBlock());
	public static final RegistryObject<Block> PIN_THE_BOWTIE_ON_THE_FREDDY = REGISTRY.register("pin_the_bowtie_on_the_freddy", () -> new PinTheBowtieOnTheFreddyBlock());
	public static final RegistryObject<Block> PIN_THE_BOWTIE_ON_THE_TIE_THE_TOY_FREDDY = REGISTRY.register("pin_the_bowtie_on_the_tie_the_toy_freddy", () -> new PinTheBowtieOnTheTieTheToyFreddyBlock());
	public static final RegistryObject<Block> FOIL_PARTY_SET_1 = REGISTRY.register("foil_party_set_1", () -> new FoilPartySet1Block());
	public static final RegistryObject<Block> PAPER_PLATES = REGISTRY.register("paper_plates", () -> new PaperPlatesBlock());
	public static final RegistryObject<Block> FOIL_PARTY_SET_2 = REGISTRY.register("foil_party_set_2", () -> new FoilPartySet2Block());
	public static final RegistryObject<Block> FOIL_PARTY_SET_3 = REGISTRY.register("foil_party_set_3", () -> new FoilPartySet3Block());
	public static final RegistryObject<Block> FOIL_PARTY_SET_4 = REGISTRY.register("foil_party_set_4", () -> new FoilPartySet4Block());
	public static final RegistryObject<Block> NEON_PARTY_SET_1 = REGISTRY.register("neon_party_set_1", () -> new NeonPartySet1Block());
	public static final RegistryObject<Block> NEON_PARTY_SET_2 = REGISTRY.register("neon_party_set_2", () -> new NeonPartySet2Block());
	public static final RegistryObject<Block> NEON_PARTY_SET_3 = REGISTRY.register("neon_party_set_3", () -> new NeonPartySet3Block());
	public static final RegistryObject<Block> NEON_PARTY_SET_4 = REGISTRY.register("neon_party_set_4", () -> new NeonPartySet4Block());
	public static final RegistryObject<Block> LADDER_TOWER = REGISTRY.register("ladder_tower", () -> new LadderTowerBlock());
	public static final RegistryObject<Block> EGG_BABY = REGISTRY.register("egg_baby", () -> new EggBabyBlock());
	public static final RegistryObject<Block> BONK_A_BON = REGISTRY.register("bonk_a_bon", () -> new BonkABonBlock());
	public static final RegistryObject<Block> CARNIVAL_HOOPS = REGISTRY.register("carnival_hoops", () -> new CarnivalHoopsBlock());
	public static final RegistryObject<Block> GRAVITY_VORTEX_2 = REGISTRY.register("gravity_vortex_2", () -> new GravityVortex2Block());
	public static final RegistryObject<Block> PICKLES = REGISTRY.register("pickles", () -> new PicklesBlock());
	public static final RegistryObject<Block> DISCOUNT_COOLING_UNIT = REGISTRY.register("discount_cooling_unit", () -> new DiscountCoolingUnitBlock());
	public static final RegistryObject<Block> BALLOON_CART = REGISTRY.register("balloon_cart", () -> new BalloonCartBlock());
	public static final RegistryObject<Block> RIDING_ROCKETS_RED = REGISTRY.register("riding_rockets_red", () -> new RidingRocketsRedBlock());
	public static final RegistryObject<Block> RIDING_ROCKETS_PURPLE = REGISTRY.register("riding_rockets_purple", () -> new RidingRocketsPurpleBlock());
	public static final RegistryObject<Block> DELUXE_SPEAKER_SET = REGISTRY.register("deluxe_speaker_set", () -> new DeluxeSpeakerSetBlock());
	public static final RegistryObject<Block> ENHANCED_SPEAKER_SET = REGISTRY.register("enhanced_speaker_set", () -> new EnhancedSpeakerSetBlock());
	public static final RegistryObject<Block> NEON_STAGE_LIGHT_GREEN = REGISTRY.register("neon_stage_light_green", () -> new NeonStageLightGreenBlock());
	public static final RegistryObject<Block> NEON_STAGE_LIGHTS_PINK = REGISTRY.register("neon_stage_lights_pink", () -> new NeonStageLightsPinkBlock());
	public static final RegistryObject<Block> NEON_STAGE_LIGHTS_BLUE = REGISTRY.register("neon_stage_lights_blue", () -> new NeonStageLightsBlueBlock());
	public static final RegistryObject<Block> NEON_STAGE_LIGHTS_ORANGE = REGISTRY.register("neon_stage_lights_orange", () -> new NeonStageLightsOrangeBlock());
	public static final RegistryObject<Block> CEILING_STAGE_LIGHTS = REGISTRY.register("ceiling_stage_lights", () -> new CeilingStageLightsBlock());
	public static final RegistryObject<Block> CEILING_STAGE_LIGHTPINK = REGISTRY.register("ceiling_stage_lightpink", () -> new CeilingStageLightpinkBlock());
	public static final RegistryObject<Block> CEILING_STAGE_LIGHTBLUE = REGISTRY.register("ceiling_stage_lightblue", () -> new CeilingStageLightblueBlock());
	public static final RegistryObject<Block> CEILING_STAGE_LIGHT_ORANGE = REGISTRY.register("ceiling_stage_light_orange", () -> new CeilingStageLightOrangeBlock());
	public static final RegistryObject<Block> NOVELTY_TRAFFIC_LIGHT = REGISTRY.register("novelty_traffic_light", () -> new NoveltyTrafficLightBlock());
	public static final RegistryObject<Block> R_FREDDY_POSTER = REGISTRY.register("r_freddy_poster", () -> new RFreddyPosterBlock());
	public static final RegistryObject<Block> RBONNIE_POSTER = REGISTRY.register("rbonnie_poster", () -> new RbonniePosterBlock());
	public static final RegistryObject<Block> R_CHICA_POSTER = REGISTRY.register("r_chica_poster", () -> new RChicaPosterBlock());
	public static final RegistryObject<Block> R_FOXY_POSTER = REGISTRY.register("r_foxy_poster", () -> new RFoxyPosterBlock());
	public static final RegistryObject<Block> LEFTY_POSTER = REGISTRY.register("lefty_poster", () -> new LeftyPosterBlock());
	public static final RegistryObject<Block> MEGAULTIMATESPEAKERTRON_3000 = REGISTRY.register("megaultimatespeakertron_3000", () -> new Megaultimatespeakertron3000Block());
	public static final RegistryObject<Block> HEAVY_DUITY_DOOR = REGISTRY.register("heavy_duity_door", () -> new HeavyDuityDoorBlock());
	public static final RegistryObject<Block> STREAMER_FIZTIME = REGISTRY.register("streamer_fiztime", () -> new StreamerFiztimeBlock());
	public static final RegistryObject<Block> MONITOR_SCAI_1 = REGISTRY.register("monitor_scai_1", () -> new MonitorScai1Block());
	public static final RegistryObject<Block> MONITOR_SCAI_2 = REGISTRY.register("monitor_scai_2", () -> new MonitorScai2Block());
	public static final RegistryObject<Block> MONITOR_SCAI_3 = REGISTRY.register("monitor_scai_3", () -> new MonitorScai3Block());
	public static final RegistryObject<Block> MONITOR_SCAI_4 = REGISTRY.register("monitor_scai_4", () -> new MonitorScai4Block());
	public static final RegistryObject<Block> MONITOR_SCAI_5 = REGISTRY.register("monitor_scai_5", () -> new MonitorScai5Block());
	public static final RegistryObject<Block> MONITOR_SCAI_6 = REGISTRY.register("monitor_scai_6", () -> new MonitorScai6Block());
	public static final RegistryObject<Block> MONITOR_SCAI_7 = REGISTRY.register("monitor_scai_7", () -> new MonitorScai7Block());
	public static final RegistryObject<Block> MONITOR_SCAI_8 = REGISTRY.register("monitor_scai_8", () -> new MonitorScai8Block());
	public static final RegistryObject<Block> FREDBEAR_MURAL = REGISTRY.register("fredbear_mural", () -> new FredbearMuralBlock());
	public static final RegistryObject<Block> PIZZA_BOX_85_OPEN = REGISTRY.register("pizza_box_85_open", () -> new PizzaBox85OpenBlock());
	public static final RegistryObject<Block> PIZZA_BOX_87_OPEN = REGISTRY.register("pizza_box_87_open", () -> new PizzaBox87OpenBlock());
	public static final RegistryObject<Block> PIZZA_BOX_93_OPEN = REGISTRY.register("pizza_box_93_open", () -> new PizzaBox93OpenBlock());
	public static final RegistryObject<Block> PIZZA_BOX_24_OPEN = REGISTRY.register("pizza_box_24_open", () -> new PizzaBox24OpenBlock());
	public static final RegistryObject<Block> NEON_JUKE_BOX_OFF = REGISTRY.register("neon_juke_box_off", () -> new NeonJukeBoxOffBlock());
	public static final RegistryObject<Block> CANDY_CADET = REGISTRY.register("candy_cadet", () -> new CandyCadetBlock());
	public static final RegistryObject<Block> BITE_FRED_BEAR_CUTOUT = REGISTRY.register("bite_fred_bear_cutout", () -> new BiteFredBearCutoutBlock());
	public static final RegistryObject<Block> MOLDY_RABBIT = REGISTRY.register("moldy_rabbit", () -> new MoldyRabbitBlock());
	public static final RegistryObject<Block> PAN_STAN = REGISTRY.register("pan_stan", () -> new PanStanBlock());
	public static final RegistryObject<Block> BUCKET_BOB = REGISTRY.register("bucket_bob", () -> new BucketBobBlock());
	public static final RegistryObject<Block> MR_CAN_DO = REGISTRY.register("mr_can_do", () -> new MrCanDoBlock());
	public static final RegistryObject<Block> MR_HUGS = REGISTRY.register("mr_hugs", () -> new MrHugsBlock());
	public static final RegistryObject<Block> NUMBER_1_CRATE = REGISTRY.register("number_1_crate", () -> new Number1CrateBlock());
	public static final RegistryObject<Block> BAGGY_MAGGIE = REGISTRY.register("baggy_maggie", () -> new BaggyMaggieBlock());
	public static final RegistryObject<Block> HAPPY_FROG = REGISTRY.register("happy_frog", () -> new HappyFrogBlock());
	public static final RegistryObject<Block> MR_HIPPO = REGISTRY.register("mr_hippo", () -> new MrHippoBlock());
	public static final RegistryObject<Block> NEDD_BEAR = REGISTRY.register("nedd_bear", () -> new NeddBearBlock());
	public static final RegistryObject<Block> PIG_PATCH = REGISTRY.register("pig_patch", () -> new PigPatchBlock());
	public static final RegistryObject<Block> ROCK_STAR_BONNIE = REGISTRY.register("rock_star_bonnie", () -> new RockStarBonnieBlock());
	public static final RegistryObject<Block> ROCK_STAR_CHICA = REGISTRY.register("rock_star_chica", () -> new RockStarChicaBlock());
	public static final RegistryObject<Block> ROCK_STAR_FREDDY = REGISTRY.register("rock_star_freddy", () -> new RockStarFreddyBlock());
	public static final RegistryObject<Block> ROCK_STAR_FOXY = REGISTRY.register("rock_star_foxy", () -> new RockStarFoxyBlock());
	public static final RegistryObject<Block> LEFTY = REGISTRY.register("lefty", () -> new LeftyBlock());
	public static final RegistryObject<Block> ORVILLE = REGISTRY.register("orville", () -> new OrvilleBlock());
	public static final RegistryObject<Block> SECURITY_PUPPET = REGISTRY.register("security_puppet", () -> new SecurityPuppetBlock());
	public static final RegistryObject<Block> PUPPET_BOX = REGISTRY.register("puppet_box", () -> new PuppetBoxBlock());
	public static final RegistryObject<Block> EL_CHIP = REGISTRY.register("el_chip", () -> new ElChipBlock());
	public static final RegistryObject<Block> MUSIC_MAN = REGISTRY.register("music_man", () -> new MusicManBlock());
	public static final RegistryObject<Block> FUN_TIME_CHICA = REGISTRY.register("fun_time_chica", () -> new FunTimeChicaBlock());
	public static final RegistryObject<Block> PRIZE_KING = REGISTRY.register("prize_king", () -> new PrizeKingBlock());
	public static final RegistryObject<Block> MOLTEN_FREDDY = REGISTRY.register("molten_freddy", () -> new MoltenFreddyBlock());
	public static final RegistryObject<Block> MOLTEN_SIT = REGISTRY.register("molten_sit", () -> new MoltenSitBlock());
	public static final RegistryObject<Block> IGNITED_CHICA = REGISTRY.register("ignited_chica", () -> new IgnitedChicaBlock());
	public static final RegistryObject<Block> THE_MANGLE = REGISTRY.register("the_mangle", () -> new TheMangleBlock());
	public static final RegistryObject<Block> BARRY_POLAR_FIXED = REGISTRY.register("barry_polar_fixed", () -> new BarryPolarFixedBlock());
	public static final RegistryObject<Block> BARRY_POLAR = REGISTRY.register("barry_polar", () -> new BarryPolarBlock());
	public static final RegistryObject<Block> FUNTIME_DELILAHBLOCK = REGISTRY.register("funtime_delilahblock", () -> new FuntimeDelilahblockBlock());
	public static final RegistryObject<Block> WALLY_WALRUS = REGISTRY.register("wally_walrus", () -> new WallyWalrusBlock());
	public static final RegistryObject<Block> PUFFY_PUFFINS = REGISTRY.register("puffy_puffins", () -> new PuffyPuffinsBlock());
	public static final RegistryObject<Block> HAZY_REINDEER = REGISTRY.register("hazy_reindeer", () -> new HazyReindeerBlock());
	public static final RegistryObject<Block> WITHERED_WALLY_WALRUS = REGISTRY.register("withered_wally_walrus", () -> new WitheredWallyWalrusBlock());
	public static final RegistryObject<Block> WITHERED_PUFFY_PUFFINS = REGISTRY.register("withered_puffy_puffins", () -> new WitheredPuffyPuffinsBlock());
	public static final RegistryObject<Block> WITHERED_HAZY_REINDEER = REGISTRY.register("withered_hazy_reindeer", () -> new WitheredHazyReindeerBlock());
	public static final RegistryObject<Block> GT_ENDO = REGISTRY.register("gt_endo", () -> new GtEndoBlock());
	public static final RegistryObject<Block> ST_ENDO = REGISTRY.register("st_endo", () -> new StEndoBlock());
	public static final RegistryObject<Block> BUFFET_ENDO = REGISTRY.register("buffet_endo", () -> new BuffetEndoBlock());
	public static final RegistryObject<Block> DR_TEATH = REGISTRY.register("dr_teath", () -> new DrTeathBlock());
	public static final RegistryObject<Block> RUSTY = REGISTRY.register("rusty", () -> new RustyBlock());
	public static final RegistryObject<Block> WINK_SIGN = REGISTRY.register("wink_sign", () -> new WinkSignBlock());
	public static final RegistryObject<Block> SCRAP_TRAP = REGISTRY.register("scrap_trap", () -> new ScrapTrapBlock());
	public static final RegistryObject<Block> BALLOON_BOY = REGISTRY.register("balloon_boy", () -> new BalloonBoyBlock());
	public static final RegistryObject<Block> BON_BON = REGISTRY.register("bon_bon", () -> new BonBonBlock());
	public static final RegistryObject<Block> BONNET = REGISTRY.register("bonnet", () -> new BonnetBlock());
	public static final RegistryObject<Block> FT_FOXY = REGISTRY.register("ft_foxy", () -> new FtFoxyBlock());
	public static final RegistryObject<Block> LOL_BIT = REGISTRY.register("lol_bit", () -> new LolBitBlock());
	public static final RegistryObject<Block> LOL_BIT_DT = REGISTRY.register("lol_bit_dt", () -> new LolBitDtBlock());
	public static final RegistryObject<Block> RETRO_CHICA = REGISTRY.register("retro_chica", () -> new RetroChicaBlock());
	public static final RegistryObject<Block> FREDDY_FAZ_BEAR = REGISTRY.register("freddy_faz_bear", () -> new FreddyFazBearBlock());
	public static final RegistryObject<Block> BONNIE = REGISTRY.register("bonnie", () -> new BonnieBlock());
	public static final RegistryObject<Block> CHICA = REGISTRY.register("chica", () -> new ChicaBlock());
	public static final RegistryObject<Block> FOXY = REGISTRY.register("foxy", () -> new FoxyBlock());
	public static final RegistryObject<Block> ENDO_01 = REGISTRY.register("endo_01", () -> new Endo01Block());
	public static final RegistryObject<Block> TOY_FREDDY = REGISTRY.register("toy_freddy", () -> new ToyFreddyBlock());
	public static final RegistryObject<Block> TOY_BONNIE = REGISTRY.register("toy_bonnie", () -> new ToyBonnieBlock());
	public static final RegistryObject<Block> TOY_CHICA = REGISTRY.register("toy_chica", () -> new ToyChicaBlock());
	public static final RegistryObject<Block> TOY_FOXY = REGISTRY.register("toy_foxy", () -> new ToyFoxyBlock());
	public static final RegistryObject<Block> ENDO_02 = REGISTRY.register("endo_02", () -> new Endo02Block());
	public static final RegistryObject<Block> DOUG_THE_DOG = REGISTRY.register("doug_the_dog", () -> new DougTheDogBlock());
	public static final RegistryObject<Block> WITHERED_DOUG_THE_DOG = REGISTRY.register("withered_doug_the_dog", () -> new WitheredDougTheDogBlock());
	public static final RegistryObject<Block> LOL_BIT_409 = REGISTRY.register("lol_bit_409", () -> new LolBit409Block());
	public static final RegistryObject<Block> JOLLY_THE_RAT = REGISTRY.register("jolly_the_rat", () -> new JollyTheRatBlock());
	public static final RegistryObject<Block> SALVAGED_JOLLY = REGISTRY.register("salvaged_jolly", () -> new SalvagedJollyBlock());
	public static final RegistryObject<Block> CHICA_O_LANTERN = REGISTRY.register("chica_o_lantern", () -> new ChicaOLanternBlock());
	public static final RegistryObject<Block> BLACK_WHITE_TILES = REGISTRY.register("black_white_tiles", () -> new BlackWhiteTilesBlock());
	public static final RegistryObject<Block> BLACK_RED_TILES = REGISTRY.register("black_red_tiles", () -> new BlackRedTilesBlock());
	public static final RegistryObject<Block> BLUE_WHITE_TILES = REGISTRY.register("blue_white_tiles", () -> new BlueWhiteTilesBlock());
	public static final RegistryObject<Block> FULL_WHITE_TILES = REGISTRY.register("full_white_tiles", () -> new FullWhiteTilesBlock());
	public static final RegistryObject<Block> RED_WHITE_TILES = REGISTRY.register("red_white_tiles", () -> new RedWhiteTilesBlock());
	public static final RegistryObject<Block> FULL_BLACK_TILES = REGISTRY.register("full_black_tiles", () -> new FullBlackTilesBlock());
	public static final RegistryObject<Block> BLACK_BLUE_TILES = REGISTRY.register("black_blue_tiles", () -> new BlackBlueTilesBlock());
	public static final RegistryObject<Block> RED_BLUE_TILES = REGISTRY.register("red_blue_tiles", () -> new RedBlueTilesBlock());
	public static final RegistryObject<Block> BLACK_WHITE_TILES_SLAB = REGISTRY.register("black_white_tiles_slab", () -> new BlackWhiteTilesSlabBlock());
	public static final RegistryObject<Block> BLACK_RED_TILES_SLAB = REGISTRY.register("black_red_tiles_slab", () -> new BlackRedTilesSlabBlock());
	public static final RegistryObject<Block> BLUE_WHITE_TILES_SLAB = REGISTRY.register("blue_white_tiles_slab", () -> new BlueWhiteTilesSlabBlock());
	public static final RegistryObject<Block> FULL_WHITE_TILES_SLAB = REGISTRY.register("full_white_tiles_slab", () -> new FullWhiteTilesSlabBlock());
	public static final RegistryObject<Block> RED_WHITE_TILES_SLAB = REGISTRY.register("red_white_tiles_slab", () -> new RedWhiteTilesSlabBlock());
	public static final RegistryObject<Block> FULL_BLACK_TILES_SLAB = REGISTRY.register("full_black_tiles_slab", () -> new FullBlackTilesSlabBlock());
	public static final RegistryObject<Block> BLACK_BLUE_TILES_SLAB = REGISTRY.register("black_blue_tiles_slab", () -> new BlackBlueTilesSlabBlock());
	public static final RegistryObject<Block> RED_BLUE_TILES_SLAB = REGISTRY.register("red_blue_tiles_slab", () -> new RedBlueTilesSlabBlock());
	public static final RegistryObject<Block> BLACK_WHITE_TILES_STAIRS = REGISTRY.register("black_white_tiles_stairs", () -> new BlackWhiteTilesStairsBlock());
	public static final RegistryObject<Block> BLACK_RED_TILES_STAIRS = REGISTRY.register("black_red_tiles_stairs", () -> new BlackRedTilesStairsBlock());
	public static final RegistryObject<Block> BLUE_WHITE_TILES_STAIRS = REGISTRY.register("blue_white_tiles_stairs", () -> new BlueWhiteTilesStairsBlock());
	public static final RegistryObject<Block> FULL_WHITE_TILES_STAIRS = REGISTRY.register("full_white_tiles_stairs", () -> new FullWhiteTilesStairsBlock());
	public static final RegistryObject<Block> RED_WHITE_TILES_STAIRS = REGISTRY.register("red_white_tiles_stairs", () -> new RedWhiteTilesStairsBlock());
	public static final RegistryObject<Block> FULL_BLACK_TILES_STAIRS = REGISTRY.register("full_black_tiles_stairs", () -> new FullBlackTilesStairsBlock());
	public static final RegistryObject<Block> BLACK_BLUE_TILES_STAIRS = REGISTRY.register("black_blue_tiles_stairs", () -> new BlackBlueTilesStairsBlock());
	public static final RegistryObject<Block> RED_BLUE_TILES_STAIRS = REGISTRY.register("red_blue_tiles_stairs", () -> new RedBlueTilesStairsBlock());
	public static final RegistryObject<Block> LARGE_BLACK_WHITE_TILES = REGISTRY.register("large_black_white_tiles", () -> new LargeBlackWhiteTilesBlock());
	public static final RegistryObject<Block> BOX = REGISTRY.register("box", () -> new BoxBlock());
	public static final RegistryObject<Block> BRANDED_BOX = REGISTRY.register("branded_box", () -> new BrandedBoxBlock());
	public static final RegistryObject<Block> RED_WALL = REGISTRY.register("red_wall", () -> new RedWallBlock());
	public static final RegistryObject<Block> POSH_WALL_TILES = REGISTRY.register("posh_wall_tiles", () -> new PoshWallTilesBlock());
	public static final RegistryObject<Block> RED_WALL_TOP = REGISTRY.register("red_wall_top", () -> new RedWallTopBlock());
	public static final RegistryObject<Block> ORANGE_WALL = REGISTRY.register("orange_wall", () -> new OrangeWallBlock());
	public static final RegistryObject<Block> YELLOW_WALLS = REGISTRY.register("yellow_walls", () -> new YellowWallsBlock());
	public static final RegistryObject<Block> LIME_WALL = REGISTRY.register("lime_wall", () -> new LimeWallBlock());
	public static final RegistryObject<Block> GREEN_WALL = REGISTRY.register("green_wall", () -> new GreenWallBlock());
	public static final RegistryObject<Block> CYAN_WALL = REGISTRY.register("cyan_wall", () -> new CyanWallBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_WALL = REGISTRY.register("light_blue_wall", () -> new LightBlueWallBlock());
	public static final RegistryObject<Block> BLUE_WALL = REGISTRY.register("blue_wall", () -> new BlueWallBlock());
	public static final RegistryObject<Block> PURPLE_WALL = REGISTRY.register("purple_wall", () -> new PurpleWallBlock());
	public static final RegistryObject<Block> MAGENTA_WALL = REGISTRY.register("magenta_wall", () -> new MagentaWallBlock());
	public static final RegistryObject<Block> PINK_WALL = REGISTRY.register("pink_wall", () -> new PinkWallBlock());
	public static final RegistryObject<Block> GRAY_WALL = REGISTRY.register("gray_wall", () -> new GrayWallBlock());
	public static final RegistryObject<Block> DARK_GRAY_WALL = REGISTRY.register("dark_gray_wall", () -> new DarkGrayWallBlock());
	public static final RegistryObject<Block> WHITE_WALL = REGISTRY.register("white_wall", () -> new WhiteWallBlock());
	public static final RegistryObject<Block> BLACK_WALL = REGISTRY.register("black_wall", () -> new BlackWallBlock());
	public static final RegistryObject<Block> RED_CURTAIN = REGISTRY.register("red_curtain", () -> new RedCurtainBlock());
	public static final RegistryObject<Block> THIN_RED_CURTAIN = REGISTRY.register("thin_red_curtain", () -> new ThinRedCurtainBlock());
	public static final RegistryObject<Block> ORANGE_CURTAIN = REGISTRY.register("orange_curtain", () -> new OrangeCurtainBlock());
	public static final RegistryObject<Block> THIN_ORANGE_CURTAIN = REGISTRY.register("thin_orange_curtain", () -> new ThinOrangeCurtainBlock());
	public static final RegistryObject<Block> YELLOW_CURTAIN = REGISTRY.register("yellow_curtain", () -> new YellowCurtainBlock());
	public static final RegistryObject<Block> THIN_YELLOW_CURTAIN = REGISTRY.register("thin_yellow_curtain", () -> new ThinYellowCurtainBlock());
	public static final RegistryObject<Block> LIME_CURTAIN = REGISTRY.register("lime_curtain", () -> new LimeCurtainBlock());
	public static final RegistryObject<Block> THIN_LIME_CURTAIN = REGISTRY.register("thin_lime_curtain", () -> new ThinLimeCurtainBlock());
	public static final RegistryObject<Block> GREEN_CURTAIN = REGISTRY.register("green_curtain", () -> new GreenCurtainBlock());
	public static final RegistryObject<Block> THIN_GREEN_CURTAIN = REGISTRY.register("thin_green_curtain", () -> new ThinGreenCurtainBlock());
	public static final RegistryObject<Block> CYAN_CURTAIN = REGISTRY.register("cyan_curtain", () -> new CyanCurtainBlock());
	public static final RegistryObject<Block> THIN_CYAN_CURTAIN = REGISTRY.register("thin_cyan_curtain", () -> new ThinCyanCurtainBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_CURTAIN = REGISTRY.register("light_blue_curtain", () -> new LightBlueCurtainBlock());
	public static final RegistryObject<Block> THIN_LIGHT_BLUE_CURTAIN = REGISTRY.register("thin_light_blue_curtain", () -> new ThinLightBlueCurtainBlock());
	public static final RegistryObject<Block> BLUE_CURTAIN = REGISTRY.register("blue_curtain", () -> new BlueCurtainBlock());
	public static final RegistryObject<Block> THIN_BLUE_CURTAIN = REGISTRY.register("thin_blue_curtain", () -> new ThinBlueCurtainBlock());
	public static final RegistryObject<Block> PURPLE_CURTAIN = REGISTRY.register("purple_curtain", () -> new PurpleCurtainBlock());
	public static final RegistryObject<Block> THIN_PURPLE_CURTAIN = REGISTRY.register("thin_purple_curtain", () -> new ThinPurpleCurtainBlock());
	public static final RegistryObject<Block> MAGENTA_CURTAIN = REGISTRY.register("magenta_curtain", () -> new MagentaCurtainBlock());
	public static final RegistryObject<Block> THIN_MAGENTA_CURTAIN = REGISTRY.register("thin_magenta_curtain", () -> new ThinMagentaCurtainBlock());
	public static final RegistryObject<Block> PINK_CURTAIN = REGISTRY.register("pink_curtain", () -> new PinkCurtainBlock());
	public static final RegistryObject<Block> THIN_PINK_CURTAIN = REGISTRY.register("thin_pink_curtain", () -> new ThinPinkCurtainBlock());
	public static final RegistryObject<Block> BROWN_CURTAIN = REGISTRY.register("brown_curtain", () -> new BrownCurtainBlock());
	public static final RegistryObject<Block> THIN_BROWN_CURTAIN = REGISTRY.register("thin_brown_curtain", () -> new ThinBrownCurtainBlock());
	public static final RegistryObject<Block> BLACK_CURTAIN = REGISTRY.register("black_curtain", () -> new BlackCurtainBlock());
	public static final RegistryObject<Block> THIN_BLACK_CURTAIN = REGISTRY.register("thin_black_curtain", () -> new ThinBlackCurtainBlock());
	public static final RegistryObject<Block> GRAY_CURTAIN = REGISTRY.register("gray_curtain", () -> new GrayCurtainBlock());
	public static final RegistryObject<Block> THIN_GRAY_CURTAIN = REGISTRY.register("thin_gray_curtain", () -> new ThinGrayCurtainBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_CURTAIN = REGISTRY.register("light_gray_curtain", () -> new LightGrayCurtainBlock());
	public static final RegistryObject<Block> THIN_LIGHT_GRAY_CURTAIN = REGISTRY.register("thin_light_gray_curtain", () -> new ThinLightGrayCurtainBlock());
	public static final RegistryObject<Block> WHITE_CURTAIN = REGISTRY.register("white_curtain", () -> new WhiteCurtainBlock());
	public static final RegistryObject<Block> THIN_WHITE_CURTAIN = REGISTRY.register("thin_white_curtain", () -> new ThinWhiteCurtainBlock());
	public static final RegistryObject<Block> RED_STAGE_BRICKS = REGISTRY.register("red_stage_bricks", () -> new RedStageBricksBlock());
	public static final RegistryObject<Block> ORANGE_STAGE_BRICKS = REGISTRY.register("orange_stage_bricks", () -> new OrangeStageBricksBlock());
	public static final RegistryObject<Block> YELLOW_STAGE_BRICKS = REGISTRY.register("yellow_stage_bricks", () -> new YellowStageBricksBlock());
	public static final RegistryObject<Block> LIME_STAGE_BRICKS = REGISTRY.register("lime_stage_bricks", () -> new LimeBricksBlock());
	public static final RegistryObject<Block> GREEN_STAGE_BRICKS = REGISTRY.register("green_stage_bricks", () -> new GreenStageBricksBlock());
	public static final RegistryObject<Block> CYAN_STAGE_BRICKS = REGISTRY.register("cyan_stage_bricks", () -> new CyanStageBricksBlock());
	public static final RegistryObject<Block> BLUE_STAGE_BRICKS = REGISTRY.register("blue_stage_bricks", () -> new BlueStageBricksBlock());
	public static final RegistryObject<Block> PURPLE_STAGE_BRICKS = REGISTRY.register("purple_stage_bricks", () -> new PurpleStageBricksBlock());
	public static final RegistryObject<Block> MAGENTA_STAGE_BRICKS = REGISTRY.register("magenta_stage_bricks", () -> new MagentaStageBricksBlock());
	public static final RegistryObject<Block> PINK_STAGE_BRICKS = REGISTRY.register("pink_stage_bricks", () -> new PinkStageBricksBlock());
	public static final RegistryObject<Block> BROWN_STAGE_BRICKS = REGISTRY.register("brown_stage_bricks", () -> new BrownStageBricksBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_BRICKS = REGISTRY.register("light_gray_bricks", () -> new LightGrayBricksBlock());
	public static final RegistryObject<Block> GRAY_STAGE_BRICKS = REGISTRY.register("gray_stage_bricks", () -> new GrayStageBricksBlock());
	public static final RegistryObject<Block> WHITE_STAGE_BRICKS = REGISTRY.register("white_stage_bricks", () -> new WhiteStageBricksBlock());
	public static final RegistryObject<Block> BLACK_STAGE_BRICKS = REGISTRY.register("black_stage_bricks", () -> new BlackStageBricksBlock());
	public static final RegistryObject<Block> CEILING_TILES = REGISTRY.register("ceiling_tiles", () -> new CeilingTilesBlock());
	public static final RegistryObject<Block> CEILING_LIGHT = REGISTRY.register("ceiling_light", () -> new CeilingLightBlock());
	public static final RegistryObject<Block> GLASS_OFFICE_DOOR = REGISTRY.register("glass_office_door", () -> new GlassOfficeDoorBlock());
	public static final RegistryObject<Block> GLASS_OFFICE_DOOR_TEXT = REGISTRY.register("glass_office_door_text", () -> new GlassOfficeDoorTextBlock());
	public static final RegistryObject<Block> GLASS_DOOR = REGISTRY.register("glass_door", () -> new GlassDoorBlock());
	public static final RegistryObject<Block> BLANK_STAFF_DOOR = REGISTRY.register("blank_staff_door", () -> new BlankStaffDoorBlock());
	public static final RegistryObject<Block> STAFF_DOOR = REGISTRY.register("staff_door", () -> new StaffDoorBlock());
	public static final RegistryObject<Block> WHITE_STAFF_DOOR = REGISTRY.register("white_staff_door", () -> new WhiteStaffDoorBlock());
	public static final RegistryObject<Block> STALL_DOOR = REGISTRY.register("stall_door", () -> new StallDoorBlock());
	public static final RegistryObject<Block> LARGE_SIGN = REGISTRY.register("large_sign", () -> new LargeSignBlock());
	public static final RegistryObject<Block> LARGE_SIGN_2 = REGISTRY.register("large_sign_2", () -> new LargeSign2Block());
	public static final RegistryObject<Block> LARGE_SIGN_3 = REGISTRY.register("large_sign_3", () -> new LargeSign3Block());
	public static final RegistryObject<Block> LARGE_SIGN_4 = REGISTRY.register("large_sign_4", () -> new LargeSign4Block());
	public static final RegistryObject<Block> COIN = REGISTRY.register("coin", () -> new CoinBlock());
	public static final RegistryObject<Block> COINS_5 = REGISTRY.register("coins_5", () -> new Coins5Block());
	public static final RegistryObject<Block> COINS_100 = REGISTRY.register("coins_100", () -> new Coins25Block());
	public static final RegistryObject<Block> COINS_25 = REGISTRY.register("coins_25", () -> new Coins100Block());
	public static final RegistryObject<Block> COINS_1000 = REGISTRY.register("coins_1000", () -> new Coins1000Block());
	public static final RegistryObject<Block> COINS_10000 = REGISTRY.register("coins_10000", () -> new Coins10000Block());
	public static final RegistryObject<Block> IMPALA_BLOCK = REGISTRY.register("impala_block", () -> new ImpalaBlockBlock());
	public static final RegistryObject<Block> DOGE_RAM_BLOCK = REGISTRY.register("doge_ram_block", () -> new DogeRamBlockBlock());
	public static final RegistryObject<Block> STATION_WAGON_BLOCK = REGISTRY.register("station_wagon_block", () -> new StationWagonBlockBlock());
	public static final RegistryObject<Block> OLD_BONNIE = REGISTRY.register("old_bonnie", () -> new OldBonnieBlock());
	public static final RegistryObject<Block> OLD_FREDDY = REGISTRY.register("old_freddy", () -> new OldFreddyBlock());
	public static final RegistryObject<Block> OLD_CHICA = REGISTRY.register("old_chica", () -> new OldChicaBlock());
	public static final RegistryObject<Block> OLD_FOXY = REGISTRY.register("old_foxy", () -> new OldFoxyBlock());
	public static final RegistryObject<Block> D_BALLOON_BOY = REGISTRY.register("d_balloon_boy", () -> new DBalloonBoyBlock());
	public static final RegistryObject<Block> BROKEN_FREDDY = REGISTRY.register("broken_freddy", () -> new BrokenFreddyBlock());
	public static final RegistryObject<Block> BROKEN_BONNIE = REGISTRY.register("broken_bonnie", () -> new BrokenBonnieBlock());
	public static final RegistryObject<Block> BROKEN_CHICA = REGISTRY.register("broken_chica", () -> new BrokenChicaBlock());
	public static final RegistryObject<Block> RASC = REGISTRY.register("rasc", () -> new RascBlock());
	public static final RegistryObject<Block> SHRED_BEAR = REGISTRY.register("shred_bear", () -> new ShredBearBlock());
	public static final RegistryObject<Block> ROTTEN_PIT = REGISTRY.register("rotten_pit", () -> new RottenPitBlock());
	public static final RegistryObject<Block> FRIGHTS_SIGN_2 = REGISTRY.register("frights_sign_2", () -> new FrightsSign2Block());
	public static final RegistryObject<Block> PIZZA_PLACE_SIGN = REGISTRY.register("pizza_place_sign", () -> new PizzaPlaceSignBlock());
	public static final RegistryObject<Block> PIZZA_PLACE_SIGN_OLD = REGISTRY.register("pizza_place_sign_old", () -> new PizzaPlaceSignOldBlock());
	public static final RegistryObject<Block> JEFFS_PIZZA_SIGN = REGISTRY.register("jeffs_pizza_sign", () -> new JeffsPizzaSignBlock());
	public static final RegistryObject<Block> LOLBIT_RECORD = REGISTRY.register("lolbit_record", () -> new LolbitRecordBlock());
	public static final RegistryObject<Block> SIGN_DDW = REGISTRY.register("sign_ddw", () -> new SignDDWBlock());
	public static final RegistryObject<Block> SIGN_SBT = REGISTRY.register("sign_sbt", () -> new SignSBTBlock());
	public static final RegistryObject<Block> SIGN_RFA = REGISTRY.register("sign_rfa", () -> new SignRFABlock());
	public static final RegistryObject<Block> SIGN_SNS = REGISTRY.register("sign_sns", () -> new SignSNSBlock());
	public static final RegistryObject<Block> TV_OFF = REGISTRY.register("tv_off", () -> new TVOffBlock());
	public static final RegistryObject<Block> MONITOR_OFF = REGISTRY.register("monitor_off", () -> new MonitorOffBlock());
	public static final RegistryObject<Block> MONITOR_WORK = REGISTRY.register("monitor_work", () -> new MonitorWorkBlock());
	public static final RegistryObject<Block> MONITOR_LOLBIT = REGISTRY.register("monitor_lolbit", () -> new MonitorLolbitBlock());
	public static final RegistryObject<Block> MONITOR_STEPHAN = REGISTRY.register("monitor_stephan", () -> new MonitorStephanBlock());
	public static final RegistryObject<Block> MONITOR_BLUESCREEN = REGISTRY.register("monitor_bluescreen", () -> new MonitorBluescreenBlock());
	public static final RegistryObject<Block> SIGN_MS = REGISTRY.register("sign_ms", () -> new SignMSBlock());
	public static final RegistryObject<Block> SAFETY_POSTER = REGISTRY.register("safety_poster", () -> new SafetyPosterBlock());
	public static final RegistryObject<Block> SAFETY_POSTER_FREDDY = REGISTRY.register("safety_poster_freddy", () -> new SafetyPosterFreddyBlock());
	public static final RegistryObject<Block> SAFETY_POSTER_BONNIE = REGISTRY.register("safety_poster_bonnie", () -> new SafetyPosterBonnieBlock());
	public static final RegistryObject<Block> SAFETY_POSTER_CHICA = REGISTRY.register("safety_poster_chica", () -> new SafetyPosterChicaBlock());
	public static final RegistryObject<Block> SAFETY_POSTER_FOXY = REGISTRY.register("safety_poster_foxy", () -> new SafetyPosterFoxyBlock());
	public static final RegistryObject<Block> CELEBRATE_POSTER = REGISTRY.register("celebrate_poster", () -> new CelebratePosterBlock());
	public static final RegistryObject<Block> PROJECTOR = REGISTRY.register("projector", () -> new ProjectorBlock());
	public static final RegistryObject<Block> CAM = REGISTRY.register("cam", () -> new CamBlock());
	public static final RegistryObject<Block> FREDDY_CUT_OUT = REGISTRY.register("freddy_cut_out", () -> new FreddyCutOutBlock());
	public static final RegistryObject<Block> BONNIE_CUT_OUT = REGISTRY.register("bonnie_cut_out", () -> new BonnieCutOutBlock());
	public static final RegistryObject<Block> CHICA_CUT_OUT = REGISTRY.register("chica_cut_out", () -> new ChicaCutOutBlock());
	public static final RegistryObject<Block> HELPY_CUT_OUT = REGISTRY.register("helpy_cut_out", () -> new HelpyCutOutBlock());
	public static final RegistryObject<Block> FRED_BEAR_POSTER = REGISTRY.register("fred_bear_poster", () -> new FredBearPosterBlock());
	public static final RegistryObject<Block> FRED_BEAR_PIZZA_POSTER = REGISTRY.register("fred_bear_pizza_poster", () -> new FredBearPizzaPosterBlock());
	public static final RegistryObject<Block> SPRING_BONNIE_POSTER = REGISTRY.register("spring_bonnie_poster", () -> new SpringBonniePosterBlock());
	public static final RegistryObject<Block> DOC_PLUSH = REGISTRY.register("doc_plush", () -> new DocPlushBlock());
	public static final RegistryObject<Block> GARF_PLUSH = REGISTRY.register("garf_plush", () -> new GarfPlushBlock());
	public static final RegistryObject<Block> ROSEY = REGISTRY.register("rosey", () -> new RoseyBlock());
	public static final RegistryObject<Block> VESSEL = REGISTRY.register("vessel", () -> new VESSELBlock());
	public static final RegistryObject<Block> STEPHAN_PLUSH = REGISTRY.register("stephan_plush", () -> new StephanPlushBlock());
	public static final RegistryObject<Block> DOLLS = REGISTRY.register("dolls", () -> new DollsBlock());
	public static final RegistryObject<Block> BARRY_POLAR_ANIMATED = REGISTRY.register("barry_polar_animated", () -> new BarryPolarAnimatedBlock());
	public static final RegistryObject<Block> BROKEN_BARRY_POLAR_ANIMATED = REGISTRY.register("broken_barry_polar_animated", () -> new BrokenBarryPolarAnimatedBlock());
	public static final RegistryObject<Block> FUNTIME_DELILAH = REGISTRY.register("funtime_delilah", () -> new FuntimeDelilahBlock());
	public static final RegistryObject<Block> EL_CHIP_ANIMATED = REGISTRY.register("el_chip_animated", () -> new ElChipAnimatedBlock());
	public static final RegistryObject<Block> ENDO_01_ANIMATED = REGISTRY.register("endo_01_animated", () -> new Endo01AnimatedBlock());
	public static final RegistryObject<Block> FUNTIME_CHICA_ANIMATED = REGISTRY.register("funtime_chica_animated", () -> new FuntimeChicaAnimatedBlock());
	public static final RegistryObject<Block> HAPP_Y_FROG_ANIMATED = REGISTRY.register("happ_y_frog_animated", () -> new HappYFrogAnimatedBlock());
	public static final RegistryObject<Block> LEFTY_ANIMATED = REGISTRY.register("lefty_animated", () -> new LeftyAnimatedBlock());
	public static final RegistryObject<Block> MR_HIPPO_ANIMATED = REGISTRY.register("mr_hippo_animated", () -> new MrHippoAnimatedBlock());
	public static final RegistryObject<Block> MUSIC_MAN_ANIMATED = REGISTRY.register("music_man_animated", () -> new MusicManAnimatedBlock());
	public static final RegistryObject<Block> NEDD_BEAR_ANIMATED = REGISTRY.register("nedd_bear_animated", () -> new NeddBearAnimatedBlock());
	public static final RegistryObject<Block> ORVILLE_ANIMATED = REGISTRY.register("orville_animated", () -> new OrvilleAnimatedBlock());
	public static final RegistryObject<Block> PIG_PATCH_ANIMATED = REGISTRY.register("pig_patch_animated", () -> new PigPatchAnimatedBlock());
	public static final RegistryObject<Block> ROCK_STAR_BONNIE_ANIMATED = REGISTRY.register("rock_star_bonnie_animated", () -> new RockStarBonnieAnimatedBlock());
	public static final RegistryObject<Block> ROCK_STAR_CHICA_ANIMATED = REGISTRY.register("rock_star_chica_animated", () -> new RockStarChicaAnimatedBlock());
	public static final RegistryObject<Block> ROCK_STAR_FOXY_ANIMATED = REGISTRY.register("rock_star_foxy_animated", () -> new RockStarFoxyAnimatedBlock());
	public static final RegistryObject<Block> ROCK_STAR_FREDDY_ANIMATED = REGISTRY.register("rock_star_freddy_animated", () -> new RockStarFreddyAnimatedBlock());
	public static final RegistryObject<Block> RUSTY_ANIMATED = REGISTRY.register("rusty_animated", () -> new RustyAnimatedBlock());
	public static final RegistryObject<Block> NEON_JUKE_BOX = REGISTRY.register("neon_juke_box", () -> new NeonJukeBoxBlock());
	public static final RegistryObject<Block> GRAVITY_VORTEX = REGISTRY.register("gravity_vortex", () -> new GravityVortexBlock());
	public static final RegistryObject<Block> FRIGHTS_SIGN = REGISTRY.register("frights_sign", () -> new FrightsSignBlock());
	public static final RegistryObject<Block> HAZY_REINDEER_ANIMATED = REGISTRY.register("hazy_reindeer_animated", () -> new HazyReindeerAnimatedBlock());
	public static final RegistryObject<Block> WALLY_WALRUS_ANIMATED = REGISTRY.register("wally_walrus_animated", () -> new WallyWalrusAnimatedBlock());
	public static final RegistryObject<Block> PUFFY_PUFFINS_ANIMATED = REGISTRY.register("puffy_puffins_animated", () -> new PuffyPuffinsAnimatedBlock());
	public static final RegistryObject<Block> GT_ENDO_ANIMATED = REGISTRY.register("gt_endo_animated", () -> new GtEndoAnimatedBlock());
	public static final RegistryObject<Block> ST_ENDO_ANIMATED = REGISTRY.register("st_endo_animated", () -> new StEndoAnimatedBlock());
	public static final RegistryObject<Block> HEAVY_DUITY_DOOR_CLOSED = REGISTRY.register("heavy_duity_door_closed", () -> new HeavyDuityDoorClosedBlock());
	public static final RegistryObject<Block> RETRO_CHICA_ANIMATED = REGISTRY.register("retro_chica_animated", () -> new RetroChicaAnimatedBlock());
	public static final RegistryObject<Block> JOLLY_THE_RAT_ANIMATED = REGISTRY.register("jolly_the_rat_animated", () -> new JollyTheRatAnimatedBlock());
	public static final RegistryObject<Block> TV_FIZTIME_POP_SODA = REGISTRY.register("tv_fiztime_pop_soda", () -> new TVFiztimePopSodaBlock());
	public static final RegistryObject<Block> TV_FLOS_GLOSSY_FLOSS = REGISTRY.register("tv_flos_glossy_floss", () -> new TVFlosGlossyFlossBlock());
	public static final RegistryObject<Block> TV_FREDDY_AND_FRIENDS = REGISTRY.register("tv_freddy_and_friends", () -> new TVFreddyAndFriendsBlock());
	public static final RegistryObject<Block> TV_GARFIELD_SHOW = REGISTRY.register("tv_garfield_show", () -> new TVGarfieldShowBlock());
	public static final RegistryObject<Block> TV_IATR = REGISTRY.register("tv_iatr", () -> new TVIatrBlock());
	public static final RegistryObject<Block> TV_LALLIES_LOLLIES = REGISTRY.register("tv_lallies_lollies", () -> new TVLalliesLolliesBlock());
	public static final RegistryObject<Block> TV_MARTIES_PLUNGERS = REGISTRY.register("tv_marties_plungers", () -> new TVMartiesPlungersBlock());
	public static final RegistryObject<Block> TV_NEWS = REGISTRY.register("tv_news", () -> new TVNewsBlock());
	public static final RegistryObject<Block> TV_PEPPERS_PICKLED_POPCORN = REGISTRY.register("tv_peppers_pickled_popcorn", () -> new TVPeppersPickledPopcornBlock());
	public static final RegistryObject<Block> TV_WACKY_WART_PASTE = REGISTRY.register("tv_wacky_wart_paste", () -> new TVWackyWartPasteBlock());
	public static final RegistryObject<Block> TV_MARCELO = REGISTRY.register("tv_marcelo", () -> new TVMarceloBlock());
	public static final RegistryObject<Block> TV_DOUG = REGISTRY.register("tv_doug", () -> new TVDougBlock());
	public static final RegistryObject<Block> TV_SCREAM = REGISTRY.register("tv_scream", () -> new TVScreamBlock());
	public static final RegistryObject<Block> TV_JAWS = REGISTRY.register("tv_jaws", () -> new TVJawsBlock());
	public static final RegistryObject<Block> TV_KILLER_KLOWNS = REGISTRY.register("tv_killer_klowns", () -> new TVKillerKlownsBlock());
	public static final RegistryObject<Block> TV_HEMAN = REGISTRY.register("tv_heman", () -> new TVHemanBlock());
	public static final RegistryObject<Block> PIZZA_BOX_85_CLOSED = REGISTRY.register("pizza_box_85_closed", () -> new PizzaBox85ClosedBlock());
	public static final RegistryObject<Block> PIZZA_BOX_87_CLOSED = REGISTRY.register("pizza_box_87_closed", () -> new PizzaBox87ClosedBlock());
	public static final RegistryObject<Block> PIZZA_BOX_93_CLOSED = REGISTRY.register("pizza_box_93_closed", () -> new PizzaBox93ClosedBlock());
	public static final RegistryObject<Block> PIZZA_BOX_24_CLOSED = REGISTRY.register("pizza_box_24_closed", () -> new PizzaBox24ClosedBlock());
	public static final RegistryObject<Block> DOUG_THE_DOG_ANIMATED = REGISTRY.register("doug_the_dog_animated", () -> new DougTheDogAnimatedBlock());
	public static final RegistryObject<Block> CEILING_LIGHT_ON = REGISTRY.register("ceiling_light_on", () -> new CeilingLightOnBlock());
	public static final RegistryObject<Block> PROJECTION = REGISTRY.register("projection", () -> new ProjectionBlock());
	public static final RegistryObject<Block> ARCADE_FREDDY = REGISTRY.register("arcade_freddy", () -> new ArcadeFreddyBlock());
	public static final RegistryObject<Block> ARCADE_FREDDY_ON = REGISTRY.register("arcade_freddy_on", () -> new ArcadeFreddyOnBlock());
	public static final RegistryObject<Block> ARCADE_BONNIE = REGISTRY.register("arcade_bonnie", () -> new ArcadeBonnieBlock());
	public static final RegistryObject<Block> ARCADE_BONNIE_ON = REGISTRY.register("arcade_bonnie_on", () -> new ArcadeBonnieOnBlock());
	public static final RegistryObject<Block> ARCADE_FOXY = REGISTRY.register("arcade_foxy", () -> new ArcadeFoxyBlock());
	public static final RegistryObject<Block> ARCADE_FOXY_ON = REGISTRY.register("arcade_foxy_on", () -> new ArcadeFoxyOnBlock());
	public static final RegistryObject<Block> PINBALL_TOY_FREDDY = REGISTRY.register("pinball_toy_freddy", () -> new PinballToyFreddyBlock());
	public static final RegistryObject<Block> GUS_THE_PUG = REGISTRY.register("gus_the_pug", () -> new GusThePugBlock());
	public static final RegistryObject<Block> GUS_THE_PUG_ANIMATED = REGISTRY.register("gus_the_pug_animated", () -> new GusThePugAnimatedBlock());
}
