
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fbms.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.fbms.block.WitheredDougTheDogBlock;
import net.mcreator.fbms.block.WinkSignBlock;
import net.mcreator.fbms.block.VESSELBlock;
import net.mcreator.fbms.block.TvWartPasteBlock;
import net.mcreator.fbms.block.TvPopCornBlock;
import net.mcreator.fbms.block.TvOffBlock;
import net.mcreator.fbms.block.TvNewsBlock;
import net.mcreator.fbms.block.TvMartyBlock;
import net.mcreator.fbms.block.TvMarceloBlock;
import net.mcreator.fbms.block.TvLallyBlock;
import net.mcreator.fbms.block.TvIATRBlock;
import net.mcreator.fbms.block.TvFreddyNFrenBlock;
import net.mcreator.fbms.block.TvFlosBlock;
import net.mcreator.fbms.block.TvFizTimeBlock;
import net.mcreator.fbms.block.TvDougBlock;
import net.mcreator.fbms.block.TvBlock;
import net.mcreator.fbms.block.ToyFreddyBlock;
import net.mcreator.fbms.block.ToyFoxyBlock;
import net.mcreator.fbms.block.ToyChicaBlock;
import net.mcreator.fbms.block.ToyBonnieBlock;
import net.mcreator.fbms.block.TheMangleBlock;
import net.mcreator.fbms.block.StephanPlushBlock;
import net.mcreator.fbms.block.StationWagonBlockBlock;
import net.mcreator.fbms.block.ShredBearBlock;
import net.mcreator.fbms.block.SecurityPuppetBlock;
import net.mcreator.fbms.block.ScrapTrapBlock;
import net.mcreator.fbms.block.SanitationStationBlock;
import net.mcreator.fbms.block.RustyBlock;
import net.mcreator.fbms.block.RustyAnimatedBlock;
import net.mcreator.fbms.block.RottenPitBlock;
import net.mcreator.fbms.block.RoseyBlock;
import net.mcreator.fbms.block.RockStarFreddyBlock;
import net.mcreator.fbms.block.RockStarFreddyAnimatedBlock;
import net.mcreator.fbms.block.RockStarFoxyBlock;
import net.mcreator.fbms.block.RockStarFoxyAnimatedBlock;
import net.mcreator.fbms.block.RockStarChicaBlock;
import net.mcreator.fbms.block.RockStarChicaAnimatedBlock;
import net.mcreator.fbms.block.RockStarBonnieBlock;
import net.mcreator.fbms.block.RockStarBonnieAnimatedBlock;
import net.mcreator.fbms.block.RidingRocketsRedBlock;
import net.mcreator.fbms.block.RidingRocketsPurpleBlock;
import net.mcreator.fbms.block.RetroChicaBlock;
import net.mcreator.fbms.block.RbonniePosterBlock;
import net.mcreator.fbms.block.RascBlock;
import net.mcreator.fbms.block.RFreddyPosterBlock;
import net.mcreator.fbms.block.RFoxyPosterBlock;
import net.mcreator.fbms.block.RChicaPosterBlock;
import net.mcreator.fbms.block.PuppetBoxBlock;
import net.mcreator.fbms.block.PrizeKingBlock;
import net.mcreator.fbms.block.PizzaPlaceSignOldBlock;
import net.mcreator.fbms.block.PizzaPlaceSignBlock;
import net.mcreator.fbms.block.PinTheBowtieOnTheTieTheToyFreddyBlock;
import net.mcreator.fbms.block.PinTheBowtieOnTheFreddyBlock;
import net.mcreator.fbms.block.PigPatchBlock;
import net.mcreator.fbms.block.PigPatchAnimatedBlock;
import net.mcreator.fbms.block.PicklesBlock;
import net.mcreator.fbms.block.PapperPalOrvilBlock;
import net.mcreator.fbms.block.PapperPalMrHippoBlock;
import net.mcreator.fbms.block.PaperPlatesBlock;
import net.mcreator.fbms.block.PaperPalClownBlock;
import net.mcreator.fbms.block.PanStanBlock;
import net.mcreator.fbms.block.OrvilleBlock;
import net.mcreator.fbms.block.OrvilleAnimatedBlock;
import net.mcreator.fbms.block.OldFreddyBlock;
import net.mcreator.fbms.block.OldFoxyBlock;
import net.mcreator.fbms.block.OldChicaBlock;
import net.mcreator.fbms.block.OldBonnieBlock;
import net.mcreator.fbms.block.Number1CrateBlock;
import net.mcreator.fbms.block.NoveltyTrafficLightBlock;
import net.mcreator.fbms.block.NeonStageLightsPinkBlock;
import net.mcreator.fbms.block.NeonStageLightsBlueBlock;
import net.mcreator.fbms.block.NeonStageLightGreenBlock;
import net.mcreator.fbms.block.NeonPartySet4Block;
import net.mcreator.fbms.block.NeonPartySet3Block;
import net.mcreator.fbms.block.NeonPartySet2Block;
import net.mcreator.fbms.block.NeonPartySet1Block;
import net.mcreator.fbms.block.NeonJukeBoxBlock;
import net.mcreator.fbms.block.NeddBearBlock;
import net.mcreator.fbms.block.NeddBearAnimatedBlock;
import net.mcreator.fbms.block.MusicManBlock;
import net.mcreator.fbms.block.MusicManAnimatedBlock;
import net.mcreator.fbms.block.MrHugsBlock;
import net.mcreator.fbms.block.MrHippoBlock;
import net.mcreator.fbms.block.MrHippoAnimatedBlock;
import net.mcreator.fbms.block.MrCanDoBlock;
import net.mcreator.fbms.block.MonitorsStephanBlock;
import net.mcreator.fbms.block.MoltenSitBlock;
import net.mcreator.fbms.block.MoltenFreddyBlock;
import net.mcreator.fbms.block.MoldyRabbitBlock;
import net.mcreator.fbms.block.MidnightMotoristBlock;
import net.mcreator.fbms.block.LolBitDtBlock;
import net.mcreator.fbms.block.LolBitBlock;
import net.mcreator.fbms.block.LolBit409Block;
import net.mcreator.fbms.block.LemonadeClownBlock;
import net.mcreator.fbms.block.LeftyPosterBlock;
import net.mcreator.fbms.block.LeftyBlock;
import net.mcreator.fbms.block.LeftyAnimatedBlock;
import net.mcreator.fbms.block.LargeSignBlock;
import net.mcreator.fbms.block.LargeSign4Block;
import net.mcreator.fbms.block.LargeSign3Block;
import net.mcreator.fbms.block.LargeSign2Block;
import net.mcreator.fbms.block.LadderTowerBlock;
import net.mcreator.fbms.block.ImpalaBlockBlock;
import net.mcreator.fbms.block.IgnitedChicaBlock;
import net.mcreator.fbms.block.HappyFrogBlock;
import net.mcreator.fbms.block.HappYFrogAnimatedBlock;
import net.mcreator.fbms.block.GumballSwivelHandsBlock;
import net.mcreator.fbms.block.GravityVortexBlock;
import net.mcreator.fbms.block.GravityVortex2Block;
import net.mcreator.fbms.block.GarfPlushBlock;
import net.mcreator.fbms.block.FuntimeDelilahblockBlock;
import net.mcreator.fbms.block.FuntimeDelilahBlock;
import net.mcreator.fbms.block.FuntimeChicaAnimatedBlock;
import net.mcreator.fbms.block.FunTimeChicaBlock;
import net.mcreator.fbms.block.FtFoxyBlock;
import net.mcreator.fbms.block.FruityMazeBlock;
import net.mcreator.fbms.block.FruitPunchClownBlock;
import net.mcreator.fbms.block.FrightsSignBlock;
import net.mcreator.fbms.block.FrightsSign2Block;
import net.mcreator.fbms.block.FreddyFazBearBlock;
import net.mcreator.fbms.block.FoxyBlock;
import net.mcreator.fbms.block.FoilPartySet4Block;
import net.mcreator.fbms.block.FoilPartySet3Block;
import net.mcreator.fbms.block.FoilPartySet2Block;
import net.mcreator.fbms.block.FoilPartySet1Block;
import net.mcreator.fbms.block.EnhancedSpeakerSetBlock;
import net.mcreator.fbms.block.Endo02Block;
import net.mcreator.fbms.block.Endo01Block;
import net.mcreator.fbms.block.Endo01AnimatedBlock;
import net.mcreator.fbms.block.ElChipBlock;
import net.mcreator.fbms.block.ElChipAnimatedBlock;
import net.mcreator.fbms.block.EggBabyBlock;
import net.mcreator.fbms.block.DuckPondBlock;
import net.mcreator.fbms.block.DrTeathBlock;
import net.mcreator.fbms.block.DougTheDogBlock;
import net.mcreator.fbms.block.DogeRamBlockBlock;
import net.mcreator.fbms.block.DocPlushBlock;
import net.mcreator.fbms.block.DiscountCoolingUnitBlock;
import net.mcreator.fbms.block.DiscountBallpitBlock;
import net.mcreator.fbms.block.DiscoPizzaBlock;
import net.mcreator.fbms.block.DeluxeSpeakerSetBlock;
import net.mcreator.fbms.block.DeluxeBallpitBlock;
import net.mcreator.fbms.block.DBalloonBoyBlock;
import net.mcreator.fbms.block.ChicaBlock;
import net.mcreator.fbms.block.CeilingStageLightsBlock;
import net.mcreator.fbms.block.CeilingStageLightpinkBlock;
import net.mcreator.fbms.block.CeilingStageLightblueBlock;
import net.mcreator.fbms.block.CarnivalHoopsBlock;
import net.mcreator.fbms.block.CandyCadetBlock;
import net.mcreator.fbms.block.BucketBobBlock;
import net.mcreator.fbms.block.BrokenFreddyBlock;
import net.mcreator.fbms.block.BrokenChicaBlock;
import net.mcreator.fbms.block.BrokenBonnieBlock;
import net.mcreator.fbms.block.BrokenBarryPolarAnimatedBlock;
import net.mcreator.fbms.block.BonnieBlock;
import net.mcreator.fbms.block.BonnetBlock;
import net.mcreator.fbms.block.BonkABonBlock;
import net.mcreator.fbms.block.BonBonBlock;
import net.mcreator.fbms.block.BiteFredBearCutoutBlock;
import net.mcreator.fbms.block.BephAnimatedBlock;
import net.mcreator.fbms.block.BarryPolarFixedBlock;
import net.mcreator.fbms.block.BarryPolarBlock;
import net.mcreator.fbms.block.BarryPolarAnimatedBlock;
import net.mcreator.fbms.block.BalloonCartBlock;
import net.mcreator.fbms.block.BalloonBoyBlock;
import net.mcreator.fbms.block.BalloonBarrelBlock;
import net.mcreator.fbms.block.BallPitTowerBlock;
import net.mcreator.fbms.block.BaggyMaggieBlock;
import net.mcreator.fbms.FbmsMod;

public class FbmsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, FbmsMod.MODID);
	public static final RegistryObject<Block> MR_HUGS = REGISTRY.register("mr_hugs", () -> new MrHugsBlock());
	public static final RegistryObject<Block> NUMBER_1_CRATE = REGISTRY.register("number_1_crate", () -> new Number1CrateBlock());
	public static final RegistryObject<Block> BAGGY_MAGGIE = REGISTRY.register("baggy_maggie", () -> new BaggyMaggieBlock());
	public static final RegistryObject<Block> ENDO_01 = REGISTRY.register("endo_01", () -> new Endo01Block());
	public static final RegistryObject<Block> CANDY_CADET = REGISTRY.register("candy_cadet", () -> new CandyCadetBlock());
	public static final RegistryObject<Block> ROCK_STAR_FREDDY = REGISTRY.register("rock_star_freddy", () -> new RockStarFreddyBlock());
	public static final RegistryObject<Block> ROCK_STAR_BONNIE = REGISTRY.register("rock_star_bonnie", () -> new RockStarBonnieBlock());
	public static final RegistryObject<Block> ROCK_STAR_CHICA = REGISTRY.register("rock_star_chica", () -> new RockStarChicaBlock());
	public static final RegistryObject<Block> ROCK_STAR_FOXY = REGISTRY.register("rock_star_foxy", () -> new RockStarFoxyBlock());
	public static final RegistryObject<Block> LEFTY = REGISTRY.register("lefty", () -> new LeftyBlock());
	public static final RegistryObject<Block> HAPPY_FROG = REGISTRY.register("happy_frog", () -> new HappyFrogBlock());
	public static final RegistryObject<Block> MR_HIPPO = REGISTRY.register("mr_hippo", () -> new MrHippoBlock());
	public static final RegistryObject<Block> NEDD_BEAR = REGISTRY.register("nedd_bear", () -> new NeddBearBlock());
	public static final RegistryObject<Block> PIG_PATCH = REGISTRY.register("pig_patch", () -> new PigPatchBlock());
	public static final RegistryObject<Block> ORVILLE = REGISTRY.register("orville", () -> new OrvilleBlock());
	public static final RegistryObject<Block> EL_CHIP = REGISTRY.register("el_chip", () -> new ElChipBlock());
	public static final RegistryObject<Block> MUSIC_MAN = REGISTRY.register("music_man", () -> new MusicManBlock());
	public static final RegistryObject<Block> FUN_TIME_CHICA = REGISTRY.register("fun_time_chica", () -> new FunTimeChicaBlock());
	public static final RegistryObject<Block> FREDDY_FAZ_BEAR = REGISTRY.register("freddy_faz_bear", () -> new FreddyFazBearBlock());
	public static final RegistryObject<Block> SECURITY_PUPPET = REGISTRY.register("security_puppet", () -> new SecurityPuppetBlock());
	public static final RegistryObject<Block> PUPPET_BOX = REGISTRY.register("puppet_box", () -> new PuppetBoxBlock());
	public static final RegistryObject<Block> PRIZE_KING = REGISTRY.register("prize_king", () -> new PrizeKingBlock());
	public static final RegistryObject<Block> MOLTEN_FREDDY = REGISTRY.register("molten_freddy", () -> new MoltenFreddyBlock());
	public static final RegistryObject<Block> MOLTEN_SIT = REGISTRY.register("molten_sit", () -> new MoltenSitBlock());
	public static final RegistryObject<Block> IGNITED_CHICA = REGISTRY.register("ignited_chica", () -> new IgnitedChicaBlock());
	public static final RegistryObject<Block> THE_MANGLE = REGISTRY.register("the_mangle", () -> new TheMangleBlock());
	public static final RegistryObject<Block> BARRY_POLAR_FIXED = REGISTRY.register("barry_polar_fixed", () -> new BarryPolarFixedBlock());
	public static final RegistryObject<Block> BARRY_POLAR = REGISTRY.register("barry_polar", () -> new BarryPolarBlock());
	public static final RegistryObject<Block> FUNTIME_DELILAHBLOCK = REGISTRY.register("funtime_delilahblock", () -> new FuntimeDelilahblockBlock());
	public static final RegistryObject<Block> MOLDY_RABBIT = REGISTRY.register("moldy_rabbit", () -> new MoldyRabbitBlock());
	public static final RegistryObject<Block> DR_TEATH = REGISTRY.register("dr_teath", () -> new DrTeathBlock());
	public static final RegistryObject<Block> BITE_FRED_BEAR_CUTOUT = REGISTRY.register("bite_fred_bear_cutout", () -> new BiteFredBearCutoutBlock());
	public static final RegistryObject<Block> RUSTY = REGISTRY.register("rusty", () -> new RustyBlock());
	public static final RegistryObject<Block> WINK_SIGN = REGISTRY.register("wink_sign", () -> new WinkSignBlock());
	public static final RegistryObject<Block> SCRAP_TRAP = REGISTRY.register("scrap_trap", () -> new ScrapTrapBlock());
	public static final RegistryObject<Block> PAN_STAN = REGISTRY.register("pan_stan", () -> new PanStanBlock());
	public static final RegistryObject<Block> BUCKET_BOB = REGISTRY.register("bucket_bob", () -> new BucketBobBlock());
	public static final RegistryObject<Block> MR_CAN_DO = REGISTRY.register("mr_can_do", () -> new MrCanDoBlock());
	public static final RegistryObject<Block> BALLOON_BOY = REGISTRY.register("balloon_boy", () -> new BalloonBoyBlock());
	public static final RegistryObject<Block> BON_BON = REGISTRY.register("bon_bon", () -> new BonBonBlock());
	public static final RegistryObject<Block> BONNET = REGISTRY.register("bonnet", () -> new BonnetBlock());
	public static final RegistryObject<Block> BONNIE = REGISTRY.register("bonnie", () -> new BonnieBlock());
	public static final RegistryObject<Block> CHICA = REGISTRY.register("chica", () -> new ChicaBlock());
	public static final RegistryObject<Block> FOXY = REGISTRY.register("foxy", () -> new FoxyBlock());
	public static final RegistryObject<Block> FT_FOXY = REGISTRY.register("ft_foxy", () -> new FtFoxyBlock());
	public static final RegistryObject<Block> LOL_BIT = REGISTRY.register("lol_bit", () -> new LolBitBlock());
	public static final RegistryObject<Block> LOL_BIT_DT = REGISTRY.register("lol_bit_dt", () -> new LolBitDtBlock());
	public static final RegistryObject<Block> RETRO_CHICA = REGISTRY.register("retro_chica", () -> new RetroChicaBlock());
	public static final RegistryObject<Block> TOY_FREDDY = REGISTRY.register("toy_freddy", () -> new ToyFreddyBlock());
	public static final RegistryObject<Block> TOY_FOXY = REGISTRY.register("toy_foxy", () -> new ToyFoxyBlock());
	public static final RegistryObject<Block> TOY_CHICA = REGISTRY.register("toy_chica", () -> new ToyChicaBlock());
	public static final RegistryObject<Block> TOY_BONNIE = REGISTRY.register("toy_bonnie", () -> new ToyBonnieBlock());
	public static final RegistryObject<Block> DOUG_THE_DOG = REGISTRY.register("doug_the_dog", () -> new DougTheDogBlock());
	public static final RegistryObject<Block> WITHERED_DOUG_THE_DOG = REGISTRY.register("withered_doug_the_dog", () -> new WitheredDougTheDogBlock());
	public static final RegistryObject<Block> ENDO_02 = REGISTRY.register("endo_02", () -> new Endo02Block());
	public static final RegistryObject<Block> LOL_BIT_409 = REGISTRY.register("lol_bit_409", () -> new LolBit409Block());
	public static final RegistryObject<Block> LARGE_SIGN = REGISTRY.register("large_sign", () -> new LargeSignBlock());
	public static final RegistryObject<Block> LARGE_SIGN_2 = REGISTRY.register("large_sign_2", () -> new LargeSign2Block());
	public static final RegistryObject<Block> LARGE_SIGN_3 = REGISTRY.register("large_sign_3", () -> new LargeSign3Block());
	public static final RegistryObject<Block> LARGE_SIGN_4 = REGISTRY.register("large_sign_4", () -> new LargeSign4Block());
	public static final RegistryObject<Block> BALLOON_BARREL = REGISTRY.register("balloon_barrel", () -> new BalloonBarrelBlock());
	public static final RegistryObject<Block> PAPER_PAL_CLOWN = REGISTRY.register("paper_pal_clown", () -> new PaperPalClownBlock());
	public static final RegistryObject<Block> PAPPER_PAL_MR_HIPPO = REGISTRY.register("papper_pal_mr_hippo", () -> new PapperPalMrHippoBlock());
	public static final RegistryObject<Block> PAPPER_PAL_ORVIL = REGISTRY.register("papper_pal_orvil", () -> new PapperPalOrvilBlock());
	public static final RegistryObject<Block> DISCOUNT_BALLPIT = REGISTRY.register("discount_ballpit", () -> new DiscountBallpitBlock());
	public static final RegistryObject<Block> DUCK_POND = REGISTRY.register("duck_pond", () -> new DuckPondBlock());
	public static final RegistryObject<Block> SANITATION_STATION = REGISTRY.register("sanitation_station", () -> new SanitationStationBlock());
	public static final RegistryObject<Block> PIN_THE_BOWTIE_ON_THE_FREDDY = REGISTRY.register("pin_the_bowtie_on_the_freddy", () -> new PinTheBowtieOnTheFreddyBlock());
	public static final RegistryObject<Block> PIN_THE_BOWTIE_ON_THE_TIE_THE_TOY_FREDDY = REGISTRY.register("pin_the_bowtie_on_the_tie_the_toy_freddy", () -> new PinTheBowtieOnTheTieTheToyFreddyBlock());
	public static final RegistryObject<Block> DELUXE_SPEAKER_SET = REGISTRY.register("deluxe_speaker_set", () -> new DeluxeSpeakerSetBlock());
	public static final RegistryObject<Block> ENHANCED_SPEAKER_SET = REGISTRY.register("enhanced_speaker_set", () -> new EnhancedSpeakerSetBlock());
	public static final RegistryObject<Block> GUMBALL_SWIVEL_HANDS = REGISTRY.register("gumball_swivel_hands", () -> new GumballSwivelHandsBlock());
	public static final RegistryObject<Block> NOVELTY_TRAFFIC_LIGHT = REGISTRY.register("novelty_traffic_light", () -> new NoveltyTrafficLightBlock());
	public static final RegistryObject<Block> MIDNIGHT_MOTORIST = REGISTRY.register("midnight_motorist", () -> new MidnightMotoristBlock());
	public static final RegistryObject<Block> FRUITY_MAZE = REGISTRY.register("fruity_maze", () -> new FruityMazeBlock());
	public static final RegistryObject<Block> FOIL_PARTY_SET_1 = REGISTRY.register("foil_party_set_1", () -> new FoilPartySet1Block());
	public static final RegistryObject<Block> FOIL_PARTY_SET_2 = REGISTRY.register("foil_party_set_2", () -> new FoilPartySet2Block());
	public static final RegistryObject<Block> FOIL_PARTY_SET_3 = REGISTRY.register("foil_party_set_3", () -> new FoilPartySet3Block());
	public static final RegistryObject<Block> FOIL_PARTY_SET_4 = REGISTRY.register("foil_party_set_4", () -> new FoilPartySet4Block());
	public static final RegistryObject<Block> NEON_JUKE_BOX = REGISTRY.register("neon_juke_box", () -> new NeonJukeBoxBlock());
	public static final RegistryObject<Block> LADDER_TOWER = REGISTRY.register("ladder_tower", () -> new LadderTowerBlock());
	public static final RegistryObject<Block> LEMONADE_CLOWN = REGISTRY.register("lemonade_clown", () -> new LemonadeClownBlock());
	public static final RegistryObject<Block> FRUIT_PUNCH_CLOWN = REGISTRY.register("fruit_punch_clown", () -> new FruitPunchClownBlock());
	public static final RegistryObject<Block> BALL_PIT_TOWER = REGISTRY.register("ball_pit_tower", () -> new BallPitTowerBlock());
	public static final RegistryObject<Block> R_FREDDY_POSTER = REGISTRY.register("r_freddy_poster", () -> new RFreddyPosterBlock());
	public static final RegistryObject<Block> RBONNIE_POSTER = REGISTRY.register("rbonnie_poster", () -> new RbonniePosterBlock());
	public static final RegistryObject<Block> R_CHICA_POSTER = REGISTRY.register("r_chica_poster", () -> new RChicaPosterBlock());
	public static final RegistryObject<Block> R_FOXY_POSTER = REGISTRY.register("r_foxy_poster", () -> new RFoxyPosterBlock());
	public static final RegistryObject<Block> NEON_PARTY_SET_1 = REGISTRY.register("neon_party_set_1", () -> new NeonPartySet1Block());
	public static final RegistryObject<Block> NEON_PARTY_SET_2 = REGISTRY.register("neon_party_set_2", () -> new NeonPartySet2Block());
	public static final RegistryObject<Block> NEON_PARTY_SET_3 = REGISTRY.register("neon_party_set_3", () -> new NeonPartySet3Block());
	public static final RegistryObject<Block> NEON_PARTY_SET_4 = REGISTRY.register("neon_party_set_4", () -> new NeonPartySet4Block());
	public static final RegistryObject<Block> LEFTY_POSTER = REGISTRY.register("lefty_poster", () -> new LeftyPosterBlock());
	public static final RegistryObject<Block> DISCO_PIZZA = REGISTRY.register("disco_pizza", () -> new DiscoPizzaBlock());
	public static final RegistryObject<Block> EGG_BABY = REGISTRY.register("egg_baby", () -> new EggBabyBlock());
	public static final RegistryObject<Block> BONK_A_BON = REGISTRY.register("bonk_a_bon", () -> new BonkABonBlock());
	public static final RegistryObject<Block> CARNIVAL_HOOPS = REGISTRY.register("carnival_hoops", () -> new CarnivalHoopsBlock());
	public static final RegistryObject<Block> GRAVITY_VORTEX_2 = REGISTRY.register("gravity_vortex_2", () -> new GravityVortex2Block());
	public static final RegistryObject<Block> PICKLES = REGISTRY.register("pickles", () -> new PicklesBlock());
	public static final RegistryObject<Block> DISCOUNT_COOLING_UNIT = REGISTRY.register("discount_cooling_unit", () -> new DiscountCoolingUnitBlock());
	public static final RegistryObject<Block> BALLOON_CART = REGISTRY.register("balloon_cart", () -> new BalloonCartBlock());
	public static final RegistryObject<Block> RIDING_ROCKETS_RED = REGISTRY.register("riding_rockets_red", () -> new RidingRocketsRedBlock());
	public static final RegistryObject<Block> RIDING_ROCKETS_PURPLE = REGISTRY.register("riding_rockets_purple", () -> new RidingRocketsPurpleBlock());
	public static final RegistryObject<Block> PAPER_PLATES = REGISTRY.register("paper_plates", () -> new PaperPlatesBlock());
	public static final RegistryObject<Block> NEON_STAGE_LIGHT_GREEN = REGISTRY.register("neon_stage_light_green", () -> new NeonStageLightGreenBlock());
	public static final RegistryObject<Block> NEON_STAGE_LIGHTS_PINK = REGISTRY.register("neon_stage_lights_pink", () -> new NeonStageLightsPinkBlock());
	public static final RegistryObject<Block> NEON_STAGE_LIGHTS_BLUE = REGISTRY.register("neon_stage_lights_blue", () -> new NeonStageLightsBlueBlock());
	public static final RegistryObject<Block> CEILING_STAGE_LIGHTS = REGISTRY.register("ceiling_stage_lights", () -> new CeilingStageLightsBlock());
	public static final RegistryObject<Block> CEILING_STAGE_LIGHTPINK = REGISTRY.register("ceiling_stage_lightpink", () -> new CeilingStageLightpinkBlock());
	public static final RegistryObject<Block> CEILING_STAGE_LIGHTBLUE = REGISTRY.register("ceiling_stage_lightblue", () -> new CeilingStageLightblueBlock());
	public static final RegistryObject<Block> DELUXE_BALLPIT = REGISTRY.register("deluxe_ballpit", () -> new DeluxeBallpitBlock());
	public static final RegistryObject<Block> IMPALA_BLOCK = REGISTRY.register("impala_block", () -> new ImpalaBlockBlock());
	public static final RegistryObject<Block> DOGE_RAM_BLOCK = REGISTRY.register("doge_ram_block", () -> new DogeRamBlockBlock());
	public static final RegistryObject<Block> STATION_WAGON_BLOCK = REGISTRY.register("station_wagon_block", () -> new StationWagonBlockBlock());
	public static final RegistryObject<Block> OLD_BONNIE = REGISTRY.register("old_bonnie", () -> new OldBonnieBlock());
	public static final RegistryObject<Block> OLD_FREDDY = REGISTRY.register("old_freddy", () -> new OldFreddyBlock());
	public static final RegistryObject<Block> OLD_CHICA = REGISTRY.register("old_chica", () -> new OldChicaBlock());
	public static final RegistryObject<Block> OLD_FOXY = REGISTRY.register("old_foxy", () -> new OldFoxyBlock());
	public static final RegistryObject<Block> D_BALLOON_BOY = REGISTRY.register("d_balloon_boy", () -> new DBalloonBoyBlock());
	public static final RegistryObject<Block> MONITORS_STEPHAN = REGISTRY.register("monitors_stephan", () -> new MonitorsStephanBlock());
	public static final RegistryObject<Block> TV_OFF = REGISTRY.register("tv_off", () -> new TvOffBlock());
	public static final RegistryObject<Block> TV = REGISTRY.register("tv", () -> new TvBlock());
	public static final RegistryObject<Block> TV_DOUG = REGISTRY.register("tv_doug", () -> new TvDougBlock());
	public static final RegistryObject<Block> TV_MARCELO = REGISTRY.register("tv_marcelo", () -> new TvMarceloBlock());
	public static final RegistryObject<Block> TV_FIZ_TIME = REGISTRY.register("tv_fiz_time", () -> new TvFizTimeBlock());
	public static final RegistryObject<Block> TV_MARTY = REGISTRY.register("tv_marty", () -> new TvMartyBlock());
	public static final RegistryObject<Block> TV_FLOS = REGISTRY.register("tv_flos", () -> new TvFlosBlock());
	public static final RegistryObject<Block> TV_WART_PASTE = REGISTRY.register("tv_wart_paste", () -> new TvWartPasteBlock());
	public static final RegistryObject<Block> TV_LALLY = REGISTRY.register("tv_lally", () -> new TvLallyBlock());
	public static final RegistryObject<Block> TV_POP_CORN = REGISTRY.register("tv_pop_corn", () -> new TvPopCornBlock());
	public static final RegistryObject<Block> TV_FREDDY_N_FREN = REGISTRY.register("tv_freddy_n_fren", () -> new TvFreddyNFrenBlock());
	public static final RegistryObject<Block> TV_IATR = REGISTRY.register("tv_iatr", () -> new TvIATRBlock());
	public static final RegistryObject<Block> TV_NEWS = REGISTRY.register("tv_news", () -> new TvNewsBlock());
	public static final RegistryObject<Block> BROKEN_FREDDY = REGISTRY.register("broken_freddy", () -> new BrokenFreddyBlock());
	public static final RegistryObject<Block> BROKEN_BONNIE = REGISTRY.register("broken_bonnie", () -> new BrokenBonnieBlock());
	public static final RegistryObject<Block> BROKEN_CHICA = REGISTRY.register("broken_chica", () -> new BrokenChicaBlock());
	public static final RegistryObject<Block> RASC = REGISTRY.register("rasc", () -> new RascBlock());
	public static final RegistryObject<Block> SHRED_BEAR = REGISTRY.register("shred_bear", () -> new ShredBearBlock());
	public static final RegistryObject<Block> ROTTEN_PIT = REGISTRY.register("rotten_pit", () -> new RottenPitBlock());
	public static final RegistryObject<Block> FRIGHTS_SIGN_2 = REGISTRY.register("frights_sign_2", () -> new FrightsSign2Block());
	public static final RegistryObject<Block> PIZZA_PLACE_SIGN = REGISTRY.register("pizza_place_sign", () -> new PizzaPlaceSignBlock());
	public static final RegistryObject<Block> PIZZA_PLACE_SIGN_OLD = REGISTRY.register("pizza_place_sign_old", () -> new PizzaPlaceSignOldBlock());
	public static final RegistryObject<Block> DOC_PLUSH = REGISTRY.register("doc_plush", () -> new DocPlushBlock());
	public static final RegistryObject<Block> GARF_PLUSH = REGISTRY.register("garf_plush", () -> new GarfPlushBlock());
	public static final RegistryObject<Block> ROSEY = REGISTRY.register("rosey", () -> new RoseyBlock());
	public static final RegistryObject<Block> VESSEL = REGISTRY.register("vessel", () -> new VESSELBlock());
	public static final RegistryObject<Block> STEPHAN_PLUSH = REGISTRY.register("stephan_plush", () -> new StephanPlushBlock());
	public static final RegistryObject<Block> BARRY_POLAR_ANIMATED = REGISTRY.register("barry_polar_animated", () -> new BarryPolarAnimatedBlock());
	public static final RegistryObject<Block> BROKEN_BARRY_POLAR_ANIMATED = REGISTRY.register("broken_barry_polar_animated", () -> new BrokenBarryPolarAnimatedBlock());
	public static final RegistryObject<Block> BEPH_ANIMATED = REGISTRY.register("beph_animated", () -> new BephAnimatedBlock());
	public static final RegistryObject<Block> FUNTIME_DELILAH = REGISTRY.register("funtime_delilah", () -> new FuntimeDelilahBlock());
	public static final RegistryObject<Block> EL_CHIP_ANIMATED = REGISTRY.register("el_chip_animated", () -> new ElChipAnimatedBlock());
	public static final RegistryObject<Block> ENDO_01_ANIMATED = REGISTRY.register("endo_01_animated", () -> new Endo01AnimatedBlock());
	public static final RegistryObject<Block> FUNTIME_CHICA_ANIMATED = REGISTRY.register("funtime_chica_animated", () -> new FuntimeChicaAnimatedBlock());
	public static final RegistryObject<Block> HAPP_Y_FROG_ANIMATED = REGISTRY.register("happ_y_frog_animated", () -> new HappYFrogAnimatedBlock());
	public static final RegistryObject<Block> LEFTY_ANIMATED = REGISTRY.register("lefty_animated", () -> new LeftyAnimatedBlock());
	public static final RegistryObject<Block> MR_HIPPO_ANIMATED = REGISTRY.register("mr_hippo_animated", () -> new MrHippoAnimatedBlock());
	public static final RegistryObject<Block> MUSIC_MAN_ANIMATED = REGISTRY.register("music_man_animated", () -> new MusicManAnimatedBlock());
	public static final RegistryObject<Block> NEDD_BEAR_ANIMATED = REGISTRY.register("nedd_bear_animated", () -> new NeddBearAnimatedBlock());
	public static final RegistryObject<Block> ORVILLE_ANIMATED = REGISTRY.register("orville_animated", () -> new OrvilleAnimatedBlock());
	public static final RegistryObject<Block> PIG_PATCH_ANIMATED = REGISTRY.register("pig_patch_animated", () -> new PigPatchAnimatedBlock());
	public static final RegistryObject<Block> ROCK_STAR_BONNIE_ANIMATED = REGISTRY.register("rock_star_bonnie_animated", () -> new RockStarBonnieAnimatedBlock());
	public static final RegistryObject<Block> ROCK_STAR_CHICA_ANIMATED = REGISTRY.register("rock_star_chica_animated", () -> new RockStarChicaAnimatedBlock());
	public static final RegistryObject<Block> ROCK_STAR_FOXY_ANIMATED = REGISTRY.register("rock_star_foxy_animated", () -> new RockStarFoxyAnimatedBlock());
	public static final RegistryObject<Block> ROCK_STAR_FREDDY_ANIMATED = REGISTRY.register("rock_star_freddy_animated", () -> new RockStarFreddyAnimatedBlock());
	public static final RegistryObject<Block> RUSTY_ANIMATED = REGISTRY.register("rusty_animated", () -> new RustyAnimatedBlock());
	public static final RegistryObject<Block> GRAVITY_VORTEX = REGISTRY.register("gravity_vortex", () -> new GravityVortexBlock());
	public static final RegistryObject<Block> FRIGHTS_SIGN = REGISTRY.register("frights_sign", () -> new FrightsSignBlock());
}
